/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.resourcetag.model;


/**
 * costAttrTagKeyInfo
 */
public class CostAttrTagKeyInfo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 标签键
     */
    private String tagKey;

    /**
     * 费用属性是否设置
     */
    private Boolean costAttr;

    /**
     * 标签键是否有效
     */
    private Boolean tagKeyValid;


    /**
     * get 标签键
     *
     * @return
     */
    public String getTagKey() {
        return tagKey;
    }

    /**
     * set 标签键
     *
     * @param tagKey
     */
    public void setTagKey(String tagKey) {
        this.tagKey = tagKey;
    }

    /**
     * get 费用属性是否设置
     *
     * @return
     */
    public Boolean getCostAttr() {
        return costAttr;
    }

    /**
     * set 费用属性是否设置
     *
     * @param costAttr
     */
    public void setCostAttr(Boolean costAttr) {
        this.costAttr = costAttr;
    }

    /**
     * get 标签键是否有效
     *
     * @return
     */
    public Boolean getTagKeyValid() {
        return tagKeyValid;
    }

    /**
     * set 标签键是否有效
     *
     * @param tagKeyValid
     */
    public void setTagKeyValid(Boolean tagKeyValid) {
        this.tagKeyValid = tagKeyValid;
    }


    /**
     * set 标签键
     *
     * @param tagKey
     */
    public CostAttrTagKeyInfo tagKey(String tagKey) {
        this.tagKey = tagKey;
        return this;
    }

    /**
     * set 费用属性是否设置
     *
     * @param costAttr
     */
    public CostAttrTagKeyInfo costAttr(Boolean costAttr) {
        this.costAttr = costAttr;
        return this;
    }

    /**
     * set 标签键是否有效
     *
     * @param tagKeyValid
     */
    public CostAttrTagKeyInfo tagKeyValid(Boolean tagKeyValid) {
        this.tagKeyValid = tagKeyValid;
        return this;
    }


}