/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Live API
 * 直播管理API
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.live.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.live.model.PublishDomain;
import com.jdcloud.sdk.service.live.model.PlayDomain;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 查询指定域名相关信息
 */
public class DescribeLiveDomainDetailResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * publishDomain
     */
    private List<PublishDomain> publishDomain;

    /**
     * playDomain
     */
    private List<PlayDomain> playDomain;


    /**
     * get publishDomain
     *
     * @return
     */
    public List<PublishDomain> getPublishDomain() {
        return publishDomain;
    }

    /**
     * set publishDomain
     *
     * @param publishDomain
     */
    public void setPublishDomain(List<PublishDomain> publishDomain) {
        this.publishDomain = publishDomain;
    }

    /**
     * get playDomain
     *
     * @return
     */
    public List<PlayDomain> getPlayDomain() {
        return playDomain;
    }

    /**
     * set playDomain
     *
     * @param playDomain
     */
    public void setPlayDomain(List<PlayDomain> playDomain) {
        this.playDomain = playDomain;
    }


    /**
     * set publishDomain
     *
     * @param publishDomain
     */
    public DescribeLiveDomainDetailResult publishDomain(List<PublishDomain> publishDomain) {
        this.publishDomain = publishDomain;
        return this;
    }

    /**
     * set playDomain
     *
     * @param playDomain
     */
    public DescribeLiveDomainDetailResult playDomain(List<PlayDomain> playDomain) {
        this.playDomain = playDomain;
        return this;
    }


    /**
     * add item to publishDomain
     *
     * @param publishDomain
     */
    public void addPublishDomain(PublishDomain publishDomain) {
        if (this.publishDomain == null) {
            this.publishDomain = new ArrayList<>();
        }
        this.publishDomain.add(publishDomain);
    }

    /**
     * add item to playDomain
     *
     * @param playDomain
     */
    public void addPlayDomain(PlayDomain playDomain) {
        if (this.playDomain == null) {
            this.playDomain = new ArrayList<>();
        }
        this.playDomain.add(playDomain);
    }

}