/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Metric APIs
 * 日志服务日志监控任务相关的管理控制接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.logs.model;

import com.jdcloud.sdk.service.logs.model.MetrictaskDetailEnd;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 查询指定监控任务的详情信息
 */
public class DescribeMetricTaskResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * data
     */
    private MetrictaskDetailEnd data;


    /**
     * get data
     *
     * @return
     */
    public MetrictaskDetailEnd getData() {
        return data;
    }

    /**
     * set data
     *
     * @param data
     */
    public void setData(MetrictaskDetailEnd data) {
        this.data = data;
    }


    /**
     * set data
     *
     * @param data
     */
    public DescribeMetricTaskResult data(MetrictaskDetailEnd data) {
        this.data = data;
        return this;
    }


}