/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * LogSearch APIs
 * 日志搜索接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.logs.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.logs.model.SearchFields;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 日志检索结果直方图
 */
public class HistogramsResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 结果条数
     */
    private Long count;

    /**
     * data
     */
    
    private List<Object> data;
    /**
     * 任务进度
     */
    private String progress;

    /**
     * searchFields
     */
    private SearchFields searchFields;

    /**
     * 总数
     */
    private Long total;



    /**
     * get 结果条数
     *
     * @return
     */
    public Long getCount() {
        return count;
    }

    /**
     * set 结果条数
     *
     * @param count
     */
    public void setCount(Long count) {
        this.count = count;
    }


    /**
    * get data
    *
    * @return
    */
    public List<Object> getData() {
        return data;
    }

    /**
    * set data
    *
    * @param data
    */
    public void setData(List<Object> data) {
        this.data = data;
    }


    /**
     * get 任务进度
     *
     * @return
     */
    public String getProgress() {
        return progress;
    }

    /**
     * set 任务进度
     *
     * @param progress
     */
    public void setProgress(String progress) {
        this.progress = progress;
    }


    /**
     * get searchFields
     *
     * @return
     */
    public SearchFields getSearchFields() {
        return searchFields;
    }

    /**
     * set searchFields
     *
     * @param searchFields
     */
    public void setSearchFields(SearchFields searchFields) {
        this.searchFields = searchFields;
    }


    /**
     * get 总数
     *
     * @return
     */
    public Long getTotal() {
        return total;
    }

    /**
     * set 总数
     *
     * @param total
     */
    public void setTotal(Long total) {
        this.total = total;
    }



    /**
     * set 结果条数
     *
     * @param count
     */
    public HistogramsResult count(Long count) {
        this.count = count;
        return this;
    }


    /**
    * set data
    *
    * @param data
    */
    public HistogramsResult data(List<Object> data) {
        this.data = data;
        return this;
    }


    /**
     * set 任务进度
     *
     * @param progress
     */
    public HistogramsResult progress(String progress) {
        this.progress = progress;
        return this;
    }


    /**
     * set searchFields
     *
     * @param searchFields
     */
    public HistogramsResult searchFields(SearchFields searchFields) {
        this.searchFields = searchFields;
        return this;
    }


    /**
     * set 总数
     *
     * @param total
     */
    public HistogramsResult total(Long total) {
        this.total = total;
        return this;
    }



    /**
     * add item to data
     *
     * @param data
     */
    public void addData(Object data) {
        if (this.data == null) {
            this.data = new ArrayList<>();
        }
        this.data.add(data);
    }
}