/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.waf.model;

import com.jdcloud.sdk.annotation.Required;

/**
 * setCcRuleReq
 */
public class SetCcRuleReq  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * WAF实例id
     * Required:true
     */
    @Required
    private String wafInstanceId;

    /**
     * 域名
     * Required:true
     */
    @Required
    private String domain;

    /**
     * 规则名称
     * Required:true
     */
    @Required
    private String ruleName;

    /**
     * uri以/开头
     * Required:true
     */
    @Required
    private String uri;

    /**
     * 精确匹配0  前缀匹配1 包含匹配2 后缀匹配5
     */
    private Integer matchType;

    /**
     * 检测周期，单位是秒，[30~600]
     * Required:true
     */
    @Required
    private Integer detectPeriod;

    /**
     * ip访问次数，[1~9999999]
     * Required:true
     */
    @Required
    private Integer singleIpLimit;

    /**
     * 阻断类型 1:302跳转到指定页面 2:验证码 3:拦截返回自定义页面 4:js跳转 5:观察 6:重定向
     * Required:true
     */
    @Required
    private Integer blockType;

    /**
     * block 持续时间，单位为分钟 [1~24*60]
     * Required:true
     */
    @Required
    private Integer blockTime;

    /**
     * blockType 为3 时，为自定义页面名称，缺省为default
     */
    private String redirection;

    /**
     * cc 统计维度，ip或cookie
     */
    private String dimension;

    /**
     * cookiename, 只有当 dimension 为 cookie 时才有效
     */
    private String dmvalue;



    /**
     * get WAF实例id
     *
     * @return
     */
    public String getWafInstanceId() {
        return wafInstanceId;
    }

    /**
     * set WAF实例id
     *
     * @param wafInstanceId
     */
    public void setWafInstanceId(String wafInstanceId) {
        this.wafInstanceId = wafInstanceId;
    }


    /**
     * get 域名
     *
     * @return
     */
    public String getDomain() {
        return domain;
    }

    /**
     * set 域名
     *
     * @param domain
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }


    /**
     * get 规则名称
     *
     * @return
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * set 规则名称
     *
     * @param ruleName
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }


    /**
     * get uri以/开头
     *
     * @return
     */
    public String getUri() {
        return uri;
    }

    /**
     * set uri以/开头
     *
     * @param uri
     */
    public void setUri(String uri) {
        this.uri = uri;
    }


    /**
     * get 精确匹配0  前缀匹配1 包含匹配2 后缀匹配5
     *
     * @return
     */
    public Integer getMatchType() {
        return matchType;
    }

    /**
     * set 精确匹配0  前缀匹配1 包含匹配2 后缀匹配5
     *
     * @param matchType
     */
    public void setMatchType(Integer matchType) {
        this.matchType = matchType;
    }


    /**
     * get 检测周期，单位是秒，[30~600]
     *
     * @return
     */
    public Integer getDetectPeriod() {
        return detectPeriod;
    }

    /**
     * set 检测周期，单位是秒，[30~600]
     *
     * @param detectPeriod
     */
    public void setDetectPeriod(Integer detectPeriod) {
        this.detectPeriod = detectPeriod;
    }


    /**
     * get ip访问次数，[1~9999999]
     *
     * @return
     */
    public Integer getSingleIpLimit() {
        return singleIpLimit;
    }

    /**
     * set ip访问次数，[1~9999999]
     *
     * @param singleIpLimit
     */
    public void setSingleIpLimit(Integer singleIpLimit) {
        this.singleIpLimit = singleIpLimit;
    }


    /**
     * get 阻断类型 1:302跳转到指定页面 2:验证码 3:拦截返回自定义页面 4:js跳转 5:观察 6:重定向
     *
     * @return
     */
    public Integer getBlockType() {
        return blockType;
    }

    /**
     * set 阻断类型 1:302跳转到指定页面 2:验证码 3:拦截返回自定义页面 4:js跳转 5:观察 6:重定向
     *
     * @param blockType
     */
    public void setBlockType(Integer blockType) {
        this.blockType = blockType;
    }


    /**
     * get block 持续时间，单位为分钟 [1~24*60]
     *
     * @return
     */
    public Integer getBlockTime() {
        return blockTime;
    }

    /**
     * set block 持续时间，单位为分钟 [1~24*60]
     *
     * @param blockTime
     */
    public void setBlockTime(Integer blockTime) {
        this.blockTime = blockTime;
    }


    /**
     * get blockType 为3 时，为自定义页面名称，缺省为default
     *
     * @return
     */
    public String getRedirection() {
        return redirection;
    }

    /**
     * set blockType 为3 时，为自定义页面名称，缺省为default
     *
     * @param redirection
     */
    public void setRedirection(String redirection) {
        this.redirection = redirection;
    }


    /**
     * get cc 统计维度，ip或cookie
     *
     * @return
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * set cc 统计维度，ip或cookie
     *
     * @param dimension
     */
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }


    /**
     * get cookiename, 只有当 dimension 为 cookie 时才有效
     *
     * @return
     */
    public String getDmvalue() {
        return dmvalue;
    }

    /**
     * set cookiename, 只有当 dimension 为 cookie 时才有效
     *
     * @param dmvalue
     */
    public void setDmvalue(String dmvalue) {
        this.dmvalue = dmvalue;
    }



    /**
     * set WAF实例id
     *
     * @param wafInstanceId
     */
    public SetCcRuleReq wafInstanceId(String wafInstanceId) {
        this.wafInstanceId = wafInstanceId;
        return this;
    }


    /**
     * set 域名
     *
     * @param domain
     */
    public SetCcRuleReq domain(String domain) {
        this.domain = domain;
        return this;
    }


    /**
     * set 规则名称
     *
     * @param ruleName
     */
    public SetCcRuleReq ruleName(String ruleName) {
        this.ruleName = ruleName;
        return this;
    }


    /**
     * set uri以/开头
     *
     * @param uri
     */
    public SetCcRuleReq uri(String uri) {
        this.uri = uri;
        return this;
    }


    /**
     * set 精确匹配0  前缀匹配1 包含匹配2 后缀匹配5
     *
     * @param matchType
     */
    public SetCcRuleReq matchType(Integer matchType) {
        this.matchType = matchType;
        return this;
    }


    /**
     * set 检测周期，单位是秒，[30~600]
     *
     * @param detectPeriod
     */
    public SetCcRuleReq detectPeriod(Integer detectPeriod) {
        this.detectPeriod = detectPeriod;
        return this;
    }


    /**
     * set ip访问次数，[1~9999999]
     *
     * @param singleIpLimit
     */
    public SetCcRuleReq singleIpLimit(Integer singleIpLimit) {
        this.singleIpLimit = singleIpLimit;
        return this;
    }


    /**
     * set 阻断类型 1:302跳转到指定页面 2:验证码 3:拦截返回自定义页面 4:js跳转 5:观察 6:重定向
     *
     * @param blockType
     */
    public SetCcRuleReq blockType(Integer blockType) {
        this.blockType = blockType;
        return this;
    }


    /**
     * set block 持续时间，单位为分钟 [1~24*60]
     *
     * @param blockTime
     */
    public SetCcRuleReq blockTime(Integer blockTime) {
        this.blockTime = blockTime;
        return this;
    }


    /**
     * set blockType 为3 时，为自定义页面名称，缺省为default
     *
     * @param redirection
     */
    public SetCcRuleReq redirection(String redirection) {
        this.redirection = redirection;
        return this;
    }


    /**
     * set cc 统计维度，ip或cookie
     *
     * @param dimension
     */
    public SetCcRuleReq dimension(String dimension) {
        this.dimension = dimension;
        return this;
    }


    /**
     * set cookiename, 只有当 dimension 为 cookie 时才有效
     *
     * @param dmvalue
     */
    public SetCcRuleReq dmvalue(String dmvalue) {
        this.dmvalue = dmvalue;
        return this;
    }


}