/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.waf.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.annotation.Required;

/**
 * setCookieReq
 */
public class SetCookieReq  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * WAF实例id
     * Required:true
     */
    @Required
    private String wafInstanceId;

    /**
     * 域名
     * Required:true
     */
    @Required
    private String domain;

    /**
     * 0表示黑名单，1表示白名单
     */
    private Integer iswhite;

    /**
     * cookie配置
     * Required:true
     */
    @Required
    private List<KeyValCfg> cookies;


    /**
     * get WAF实例id
     *
     * @return
     */
    public String getWafInstanceId() {
        return wafInstanceId;
    }

    /**
     * set WAF实例id
     *
     * @param wafInstanceId
     */
    public void setWafInstanceId(String wafInstanceId) {
        this.wafInstanceId = wafInstanceId;
    }

    /**
     * get 域名
     *
     * @return
     */
    public String getDomain() {
        return domain;
    }

    /**
     * set 域名
     *
     * @param domain
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * get 0表示黑名单，1表示白名单
     *
     * @return
     */
    public Integer getIswhite() {
        return iswhite;
    }

    /**
     * set 0表示黑名单，1表示白名单
     *
     * @param iswhite
     */
    public void setIswhite(Integer iswhite) {
        this.iswhite = iswhite;
    }

    /**
     * get cookie配置
     *
     * @return
     */
    public List<KeyValCfg> getCookies() {
        return cookies;
    }

    /**
     * set cookie配置
     *
     * @param cookies
     */
    public void setCookies(List<KeyValCfg> cookies) {
        this.cookies = cookies;
    }


    /**
     * set WAF实例id
     *
     * @param wafInstanceId
     */
    public SetCookieReq wafInstanceId(String wafInstanceId) {
        this.wafInstanceId = wafInstanceId;
        return this;
    }

    /**
     * set 域名
     *
     * @param domain
     */
    public SetCookieReq domain(String domain) {
        this.domain = domain;
        return this;
    }

    /**
     * set 0表示黑名单，1表示白名单
     *
     * @param iswhite
     */
    public SetCookieReq iswhite(Integer iswhite) {
        this.iswhite = iswhite;
        return this;
    }

    /**
     * set cookie配置
     *
     * @param cookies
     */
    public SetCookieReq cookies(List<KeyValCfg> cookies) {
        this.cookies = cookies;
        return this;
    }


    /**
     * add item to cookie配置
     *
     * @param cookie
     */
    public void addCookie(KeyValCfg cookie) {
        if (this.cookies == null) {
            this.cookies = new ArrayList<>();
        }
        this.cookies.add(cookie);
    }

}