/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdaip.model;

import java.util.List;
import java.util.ArrayList;

/**
 * 管理接口推理服务详情
 */
public class AdminInferenceInfo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 推理服务实例ID
     */
    private String inferenceId;

    /**
     * 推理服务实例名称，带有版本号
     */
    private String name;

    /**
     * 推理服务服务Id
     */
    private String serviceId;

    /**
     * 推理服务服务名称
     */
    private String serviceName;

    /**
     * 应用类型
     */
    private String appType;

    /**
     * 推理服务版本状态：
&#x60;queuing&#x60;: 排队中。
&#x60;deploying&#x60;: 部署中。
&#x60;failed&#x60;: 失败。
&#x60;running&#x60;: 运行中。
&#x60;scaling&#x60;: 扩缩中。
&#x60;stopping&#x60;: 停止中。
&#x60;stopped&#x60;: 已停止。
&#x60;deleting&#x60;: 删除中。
&#x60;rolling-back&#x60;: 回滚中(不能做任何操作)。
&#x60;rolled-back&#x60;: 已回滚(只能操作删除)。

     */
    private String state;

    /**
     * 创建服务的用户
     */
    private String createUser;

    /**
     * 创建服务的用户PIN
     */
    private String createUserPin;

    /**
     * 推理服务所属工作空间ID
     */
    private String workspaceId;

    /**
     * 推理服务所属工作空间名称
     */
    private String workspaceName;

    /**
     * 用户标签
     */
    
    private List<UserTag> userTags;
    /**
     * 资源组信息
     */
    private ResourceGroupInfo resourceGroupInfo;



    /**
     * get 推理服务实例ID
     *
     * @return
     */
    public String getInferenceId() {
        return inferenceId;
    }

    /**
     * set 推理服务实例ID
     *
     * @param inferenceId
     */
    public void setInferenceId(String inferenceId) {
        this.inferenceId = inferenceId;
    }


    /**
     * get 推理服务实例名称，带有版本号
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     * set 推理服务实例名称，带有版本号
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * get 推理服务服务Id
     *
     * @return
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * set 推理服务服务Id
     *
     * @param serviceId
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }


    /**
     * get 推理服务服务名称
     *
     * @return
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * set 推理服务服务名称
     *
     * @param serviceName
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }


    /**
     * get 应用类型
     *
     * @return
     */
    public String getAppType() {
        return appType;
    }

    /**
     * set 应用类型
     *
     * @param appType
     */
    public void setAppType(String appType) {
        this.appType = appType;
    }


    /**
     * get 推理服务版本状态：
&#x60;queuing&#x60;: 排队中。
&#x60;deploying&#x60;: 部署中。
&#x60;failed&#x60;: 失败。
&#x60;running&#x60;: 运行中。
&#x60;scaling&#x60;: 扩缩中。
&#x60;stopping&#x60;: 停止中。
&#x60;stopped&#x60;: 已停止。
&#x60;deleting&#x60;: 删除中。
&#x60;rolling-back&#x60;: 回滚中(不能做任何操作)。
&#x60;rolled-back&#x60;: 已回滚(只能操作删除)。

     *
     * @return
     */
    public String getState() {
        return state;
    }

    /**
     * set 推理服务版本状态：
&#x60;queuing&#x60;: 排队中。
&#x60;deploying&#x60;: 部署中。
&#x60;failed&#x60;: 失败。
&#x60;running&#x60;: 运行中。
&#x60;scaling&#x60;: 扩缩中。
&#x60;stopping&#x60;: 停止中。
&#x60;stopped&#x60;: 已停止。
&#x60;deleting&#x60;: 删除中。
&#x60;rolling-back&#x60;: 回滚中(不能做任何操作)。
&#x60;rolled-back&#x60;: 已回滚(只能操作删除)。

     *
     * @param state
     */
    public void setState(String state) {
        this.state = state;
    }


    /**
     * get 创建服务的用户
     *
     * @return
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set 创建服务的用户
     *
     * @param createUser
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }


    /**
     * get 创建服务的用户PIN
     *
     * @return
     */
    public String getCreateUserPin() {
        return createUserPin;
    }

    /**
     * set 创建服务的用户PIN
     *
     * @param createUserPin
     */
    public void setCreateUserPin(String createUserPin) {
        this.createUserPin = createUserPin;
    }


    /**
     * get 推理服务所属工作空间ID
     *
     * @return
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * set 推理服务所属工作空间ID
     *
     * @param workspaceId
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }


    /**
     * get 推理服务所属工作空间名称
     *
     * @return
     */
    public String getWorkspaceName() {
        return workspaceName;
    }

    /**
     * set 推理服务所属工作空间名称
     *
     * @param workspaceName
     */
    public void setWorkspaceName(String workspaceName) {
        this.workspaceName = workspaceName;
    }


    /**
    * get 用户标签
    *
    * @return
    */
    public List<UserTag> getUserTags() {
        return userTags;
    }

    /**
    * set 用户标签
    *
    * @param userTags
    */
    public void setUserTags(List<UserTag> userTags) {
        this.userTags = userTags;
    }


    /**
     * get 资源组信息
     *
     * @return
     */
    public ResourceGroupInfo getResourceGroupInfo() {
        return resourceGroupInfo;
    }

    /**
     * set 资源组信息
     *
     * @param resourceGroupInfo
     */
    public void setResourceGroupInfo(ResourceGroupInfo resourceGroupInfo) {
        this.resourceGroupInfo = resourceGroupInfo;
    }



    /**
     * set 推理服务实例ID
     *
     * @param inferenceId 推理服务实例ID
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo inferenceId(String inferenceId) {
        this.inferenceId = inferenceId;
        return this;
    }


    /**
     * set 推理服务实例名称，带有版本号
     *
     * @param name 推理服务实例名称，带有版本号
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo name(String name) {
        this.name = name;
        return this;
    }


    /**
     * set 推理服务服务Id
     *
     * @param serviceId 推理服务服务Id
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo serviceId(String serviceId) {
        this.serviceId = serviceId;
        return this;
    }


    /**
     * set 推理服务服务名称
     *
     * @param serviceName 推理服务服务名称
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo serviceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }


    /**
     * set 应用类型
     *
     * @param appType 应用类型
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo appType(String appType) {
        this.appType = appType;
        return this;
    }


    /**
     * set 推理服务版本状态：
&#x60;queuing&#x60;: 排队中。
&#x60;deploying&#x60;: 部署中。
&#x60;failed&#x60;: 失败。
&#x60;running&#x60;: 运行中。
&#x60;scaling&#x60;: 扩缩中。
&#x60;stopping&#x60;: 停止中。
&#x60;stopped&#x60;: 已停止。
&#x60;deleting&#x60;: 删除中。
&#x60;rolling-back&#x60;: 回滚中(不能做任何操作)。
&#x60;rolled-back&#x60;: 已回滚(只能操作删除)。

     *
     * @param state 推理服务版本状态：
&#x60;queuing&#x60;: 排队中。
&#x60;deploying&#x60;: 部署中。
&#x60;failed&#x60;: 失败。
&#x60;running&#x60;: 运行中。
&#x60;scaling&#x60;: 扩缩中。
&#x60;stopping&#x60;: 停止中。
&#x60;stopped&#x60;: 已停止。
&#x60;deleting&#x60;: 删除中。
&#x60;rolling-back&#x60;: 回滚中(不能做任何操作)。
&#x60;rolled-back&#x60;: 已回滚(只能操作删除)。

     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo state(String state) {
        this.state = state;
        return this;
    }


    /**
     * set 创建服务的用户
     *
     * @param createUser 创建服务的用户
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo createUser(String createUser) {
        this.createUser = createUser;
        return this;
    }


    /**
     * set 创建服务的用户PIN
     *
     * @param createUserPin 创建服务的用户PIN
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo createUserPin(String createUserPin) {
        this.createUserPin = createUserPin;
        return this;
    }


    /**
     * set 推理服务所属工作空间ID
     *
     * @param workspaceId 推理服务所属工作空间ID
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo workspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }


    /**
     * set 推理服务所属工作空间名称
     *
     * @param workspaceName 推理服务所属工作空间名称
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo workspaceName(String workspaceName) {
        this.workspaceName = workspaceName;
        return this;
    }


    /**
    * set 用户标签
    *
    * @param userTags 用户标签
    * @return AdminInferenceInfo
    */
    public AdminInferenceInfo userTags(List<UserTag> userTags) {
        this.userTags = userTags;
        return this;
    }


    /**
     * set 资源组信息
     *
     * @param resourceGroupInfo 资源组信息
     * @return AdminInferenceInfo
     */
    public AdminInferenceInfo resourceGroupInfo(ResourceGroupInfo resourceGroupInfo) {
        this.resourceGroupInfo = resourceGroupInfo;
        return this;
    }



    /**
     * add item to 用户标签
     *
     * @param userTag
     */
    public void addUserTag(UserTag userTag) {
        if (this.userTags == null) {
            this.userTags = new ArrayList<>();
        }
        this.userTags.add(userTag);
    }
}