/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdaip.model;

import com.jdcloud.sdk.annotation.Required;

/**
 * 将训练完成的学生模型注册为已有模型的新版本。
 */
public class DeployStillNewModelVersion  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 已有模型的模型ID。
     * Required:true
     */
    @Required
    private String modelId;

    /**
     * 新版本描述，不超过256字符。
     * Required:true
     */
    @Required
    private String versionDesc;



    /**
     * get 已有模型的模型ID。
     *
     * @return
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * set 已有模型的模型ID。
     *
     * @param modelId
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }


    /**
     * get 新版本描述，不超过256字符。
     *
     * @return
     */
    public String getVersionDesc() {
        return versionDesc;
    }

    /**
     * set 新版本描述，不超过256字符。
     *
     * @param versionDesc
     */
    public void setVersionDesc(String versionDesc) {
        this.versionDesc = versionDesc;
    }



    /**
     * set 已有模型的模型ID。
     *
     * @param modelId 已有模型的模型ID。
     * @return DeployStillNewModelVersion
     */
    public DeployStillNewModelVersion modelId(String modelId) {
        this.modelId = modelId;
        return this;
    }


    /**
     * set 新版本描述，不超过256字符。
     *
     * @param versionDesc 新版本描述，不超过256字符。
     * @return DeployStillNewModelVersion
     */
    public DeployStillNewModelVersion versionDesc(String versionDesc) {
        this.versionDesc = versionDesc;
        return this;
    }


}