/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdaip.model;

import com.jdcloud.sdk.annotation.Required;

/**
 * 用户自定义标签，用于资源分类、筛选和成本分账。

**标签限制：**
- 最多 10 个标签
- key 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- key 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

**使用场景：**
- 项目标识：&#x60;project: llm-training&#x60;
- 团队标识：&#x60;team: ai-research&#x60;
- 环境标识：&#x60;env: production&#x60;
- 成本中心：&#x60;cost-center: cc-001&#x60;

 */
public class JobTag  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 标签键。

**命名规范：**
- 长度：1~63 个字符
- 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     * Required:true
     */
    @Required
    private String key;

    /**
     * 标签值。

**命名规范：**
- 长度：0~63 个字符
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     * Required:true
     */
    @Required
    private String value;



    /**
     * get 标签键。

**命名规范：**
- 长度：1~63 个字符
- 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @return
     */
    public String getKey() {
        return key;
    }

    /**
     * set 标签键。

**命名规范：**
- 长度：1~63 个字符
- 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @param key
     */
    public void setKey(String key) {
        this.key = key;
    }


    /**
     * get 标签值。

**命名规范：**
- 长度：0~63 个字符
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @return
     */
    public String getValue() {
        return value;
    }

    /**
     * set 标签值。

**命名规范：**
- 长度：0~63 个字符
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @param value
     */
    public void setValue(String value) {
        this.value = value;
    }



    /**
     * set 标签键。

**命名规范：**
- 长度：1~63 个字符
- 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @param key 标签键。

**命名规范：**
- 长度：1~63 个字符
- 不能以 &#x60;jrn:&#x60; 或 &#x60;jdc-&#x60; 开头
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     * @return JobTag
     */
    public JobTag key(String key) {
        this.key = key;
        return this;
    }


    /**
     * set 标签值。

**命名规范：**
- 长度：0~63 个字符
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     *
     * @param value 标签值。

**命名规范：**
- 长度：0~63 个字符
- 支持中文、大小写英文、数字及符号：&#x60;\_.,:\/&#x3D;+-@&#x60;

     * @return JobTag
     */
    public JobTag value(String value) {
        this.value = value;
        return this;
    }


}