/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * cos对象
 * JDOS Chogori vGPU OpenAPI
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdaip.model;


/**
 * subnetInfo
 */
public class SubnetInfo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 子网的网段信息
     */
    private String cidrBlock;

    /**
     * +optional
     */
    private Object extraArgs;

    /**
     * +optional
     */
    private String routeTableId;

    /**
     * 子网的ID
     */
    private String subnetId;

    /**
     * 子网所属VPC的ID
     */
    private String vpcId;



    /**
     * get 子网的网段信息
     *
     * @return
     */
    public String getCidrBlock() {
        return cidrBlock;
    }

    /**
     * set 子网的网段信息
     *
     * @param cidrBlock
     */
    public void setCidrBlock(String cidrBlock) {
        this.cidrBlock = cidrBlock;
    }


    /**
     * get +optional
     *
     * @return
     */
    public Object getExtraArgs() {
        return extraArgs;
    }

    /**
     * set +optional
     *
     * @param extraArgs
     */
    public void setExtraArgs(Object extraArgs) {
        this.extraArgs = extraArgs;
    }


    /**
     * get +optional
     *
     * @return
     */
    public String getRouteTableId() {
        return routeTableId;
    }

    /**
     * set +optional
     *
     * @param routeTableId
     */
    public void setRouteTableId(String routeTableId) {
        this.routeTableId = routeTableId;
    }


    /**
     * get 子网的ID
     *
     * @return
     */
    public String getSubnetId() {
        return subnetId;
    }

    /**
     * set 子网的ID
     *
     * @param subnetId
     */
    public void setSubnetId(String subnetId) {
        this.subnetId = subnetId;
    }


    /**
     * get 子网所属VPC的ID
     *
     * @return
     */
    public String getVpcId() {
        return vpcId;
    }

    /**
     * set 子网所属VPC的ID
     *
     * @param vpcId
     */
    public void setVpcId(String vpcId) {
        this.vpcId = vpcId;
    }



    /**
     * set 子网的网段信息
     *
     * @param cidrBlock 子网的网段信息
     * @return SubnetInfo
     */
    public SubnetInfo cidrBlock(String cidrBlock) {
        this.cidrBlock = cidrBlock;
        return this;
    }


    /**
     * set +optional
     *
     * @param extraArgs +optional
     * @return SubnetInfo
     */
    public SubnetInfo extraArgs(Object extraArgs) {
        this.extraArgs = extraArgs;
        return this;
    }


    /**
     * set +optional
     *
     * @param routeTableId +optional
     * @return SubnetInfo
     */
    public SubnetInfo routeTableId(String routeTableId) {
        this.routeTableId = routeTableId;
        return this;
    }


    /**
     * set 子网的ID
     *
     * @param subnetId 子网的ID
     * @return SubnetInfo
     */
    public SubnetInfo subnetId(String subnetId) {
        this.subnetId = subnetId;
        return this;
    }


    /**
     * set 子网所属VPC的ID
     *
     * @param vpcId 子网所属VPC的ID
     * @return SubnetInfo
     */
    public SubnetInfo vpcId(String vpcId) {
        this.vpcId = vpcId;
        return this;
    }


}