/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 资产-数据集
 * 数据集相关的操作。

详细操作说明请参考帮助文档：[资产管理-数据集](https://docs.jdcloud.com/cn/jdaip/dataset)

 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdaip.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.jdaip.model.UpdateDatasetParam;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 修改数据集信息
 */
public class UpdateDatasetRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 修改数据集的参数
     * Required:true
     */
    @Required
    private UpdateDatasetParam updateDatasetSpec;

    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 工作空间ID
     * Required:true
     */
    @Required
    private String workspaceId;

    /**
     * 数据集ID
     * Required:true
     */
    @Required
    private String datasetId;



    /**
     * get 修改数据集的参数
     *
     * @return
     */
    public UpdateDatasetParam getUpdateDatasetSpec() {
        return updateDatasetSpec;
    }

    /**
     * set 修改数据集的参数
     *
     * @param updateDatasetSpec
     */
    public void setUpdateDatasetSpec(UpdateDatasetParam updateDatasetSpec) {
        this.updateDatasetSpec = updateDatasetSpec;
    }


    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 工作空间ID
     *
     * @return
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * set 工作空间ID
     *
     * @param workspaceId
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
    }


    /**
     * get 数据集ID
     *
     * @return
     */
    public String getDatasetId() {
        return datasetId;
    }

    /**
     * set 数据集ID
     *
     * @param datasetId
     */
    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }



    /**
     * set 修改数据集的参数
     *
     * @param updateDatasetSpec 修改数据集的参数
     * @return UpdateDatasetRequest
     */
    public UpdateDatasetRequest updateDatasetSpec(UpdateDatasetParam updateDatasetSpec) {
        this.updateDatasetSpec = updateDatasetSpec;
        return this;
    }


    /**
     * set 地域ID
     *
     * @param regionId 地域ID
     * @return UpdateDatasetRequest
     */
    public UpdateDatasetRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 工作空间ID
     *
     * @param workspaceId 工作空间ID
     * @return UpdateDatasetRequest
     */
    public UpdateDatasetRequest workspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }


    /**
     * set 数据集ID
     *
     * @param datasetId 数据集ID
     * @return UpdateDatasetRequest
     */
    public UpdateDatasetRequest datasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }


}