/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Domain
 * 域名配置相关接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.vod.model;

import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 查询域名
 */
public class GetDomainResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 域名ID
     */
    private String id;

    /**
     * 域名名称
     */
    private String name;

    /**
     * 域名CNAME
     */
    private String cname;

    /**
     * 域名状态。取值范围：
  init - 初始状态
  configuring - 配置中
  normal - 正常
  stopped - 已停用

     */
    private String status;

    /**
     * 域名来源。取值范围：
  system - 系统生成
  custom - 用户自建

     */
    private String source;

    /**
     * 是否默认域名
     */
    private Boolean asDefault;

    /**
     * 创建时间
     */
    private String createTime;

    /**
     * 修改时间
     */
    private String updateTime;


    /**
     * get 域名ID
     *
     * @return
     */
    public String getId() {
        return id;
    }

    /**
     * set 域名ID
     *
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * get 域名名称
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     * set 域名名称
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * get 域名CNAME
     *
     * @return
     */
    public String getCname() {
        return cname;
    }

    /**
     * set 域名CNAME
     *
     * @param cname
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * get 域名状态。取值范围：
  init - 初始状态
  configuring - 配置中
  normal - 正常
  stopped - 已停用

     *
     * @return
     */
    public String getStatus() {
        return status;
    }

    /**
     * set 域名状态。取值范围：
  init - 初始状态
  configuring - 配置中
  normal - 正常
  stopped - 已停用

     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * get 域名来源。取值范围：
  system - 系统生成
  custom - 用户自建

     *
     * @return
     */
    public String getSource() {
        return source;
    }

    /**
     * set 域名来源。取值范围：
  system - 系统生成
  custom - 用户自建

     *
     * @param source
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * get 是否默认域名
     *
     * @return
     */
    public Boolean getAsDefault() {
        return asDefault;
    }

    /**
     * set 是否默认域名
     *
     * @param asDefault
     */
    public void setAsDefault(Boolean asDefault) {
        this.asDefault = asDefault;
    }

    /**
     * get 创建时间
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 创建时间
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * get 修改时间
     *
     * @return
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * set 修改时间
     *
     * @param updateTime
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }


    /**
     * set 域名ID
     *
     * @param id
     */
    public GetDomainResult id(String id) {
        this.id = id;
        return this;
    }

    /**
     * set 域名名称
     *
     * @param name
     */
    public GetDomainResult name(String name) {
        this.name = name;
        return this;
    }

    /**
     * set 域名CNAME
     *
     * @param cname
     */
    public GetDomainResult cname(String cname) {
        this.cname = cname;
        return this;
    }

    /**
     * set 域名状态。取值范围：
  init - 初始状态
  configuring - 配置中
  normal - 正常
  stopped - 已停用

     *
     * @param status
     */
    public GetDomainResult status(String status) {
        this.status = status;
        return this;
    }

    /**
     * set 域名来源。取值范围：
  system - 系统生成
  custom - 用户自建

     *
     * @param source
     */
    public GetDomainResult source(String source) {
        this.source = source;
        return this;
    }

    /**
     * set 是否默认域名
     *
     * @param asDefault
     */
    public GetDomainResult asDefault(Boolean asDefault) {
        this.asDefault = asDefault;
        return this;
    }

    /**
     * set 创建时间
     *
     * @param createTime
     */
    public GetDomainResult createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * set 修改时间
     *
     * @param updateTime
     */
    public GetDomainResult updateTime(String updateTime) {
        this.updateTime = updateTime;
        return this;
    }


}