/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.vod.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.annotation.Required;

/**
 * 视频剪辑媒体轨信息
 */
public class MediaTrack  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 轨类型。目前只支持的有：video，audio，text
- video：视频轨
- audio：音频轨
- text：文字轨
* 视频轨为空时，音频轨必须非空。
* 音频轨为空时，视频轨必须非空

     * Required:true
     */
    @Required
    private String trackType;

    /**
     * 视频剪辑素材片段。一个Timeline中的所有MediaClip，总共不能超过20个。
     * Required:true
     */
    @Required
    private List<MediaClip> clips;


    /**
     * get 轨类型。目前只支持的有：video，audio，text
- video：视频轨
- audio：音频轨
- text：文字轨
* 视频轨为空时，音频轨必须非空。
* 音频轨为空时，视频轨必须非空

     *
     * @return
     */
    public String getTrackType() {
        return trackType;
    }

    /**
     * set 轨类型。目前只支持的有：video，audio，text
- video：视频轨
- audio：音频轨
- text：文字轨
* 视频轨为空时，音频轨必须非空。
* 音频轨为空时，视频轨必须非空

     *
     * @param trackType
     */
    public void setTrackType(String trackType) {
        this.trackType = trackType;
    }

    /**
     * get 视频剪辑素材片段。一个Timeline中的所有MediaClip，总共不能超过20个。
     *
     * @return
     */
    public List<MediaClip> getClips() {
        return clips;
    }

    /**
     * set 视频剪辑素材片段。一个Timeline中的所有MediaClip，总共不能超过20个。
     *
     * @param clips
     */
    public void setClips(List<MediaClip> clips) {
        this.clips = clips;
    }


    /**
     * set 轨类型。目前只支持的有：video，audio，text
- video：视频轨
- audio：音频轨
- text：文字轨
* 视频轨为空时，音频轨必须非空。
* 音频轨为空时，视频轨必须非空

     *
     * @param trackType
     */
    public MediaTrack trackType(String trackType) {
        this.trackType = trackType;
        return this;
    }

    /**
     * set 视频剪辑素材片段。一个Timeline中的所有MediaClip，总共不能超过20个。
     *
     * @param clips
     */
    public MediaTrack clips(List<MediaClip> clips) {
        this.clips = clips;
        return this;
    }


    /**
     * add item to 视频剪辑素材片段。一个Timeline中的所有MediaClip，总共不能超过20个。
     *
     * @param clip
     */
    public void addClip(MediaClip clip) {
        if (this.clips == null) {
            this.clips = new ArrayList<>();
        }
        this.clips.add(clip);
    }

}