/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * applyPartner
 * 合作伙伴管理
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.partner.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * followApplyDistributorRequest
 */
public class FollowApplyDistributorRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 合作线索列表
     */
    
    private List<ApplyDistributorDTO> applyDistributorList;
    /**
     * 状态
     */
    private Integer status;

    /**
     * 状态说明
     */
    private String statusRemark;

    /**
     * 跟进时间
     */
    private String followTime;

    /**
     * 跟进人
     */
    private String followPerson;

    /**
     * 跟进说明
     */
    private String followRemark;



    /**
    * get 合作线索列表
    *
    * @return
    */
    public List<ApplyDistributorDTO> getApplyDistributorList() {
        return applyDistributorList;
    }

    /**
    * set 合作线索列表
    *
    * @param applyDistributorList
    */
    public void setApplyDistributorList(List<ApplyDistributorDTO> applyDistributorList) {
        this.applyDistributorList = applyDistributorList;
    }


    /**
     * get 状态
     *
     * @return
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * set 状态
     *
     * @param status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }


    /**
     * get 状态说明
     *
     * @return
     */
    public String getStatusRemark() {
        return statusRemark;
    }

    /**
     * set 状态说明
     *
     * @param statusRemark
     */
    public void setStatusRemark(String statusRemark) {
        this.statusRemark = statusRemark;
    }


    /**
     * get 跟进时间
     *
     * @return
     */
    public String getFollowTime() {
        return followTime;
    }

    /**
     * set 跟进时间
     *
     * @param followTime
     */
    public void setFollowTime(String followTime) {
        this.followTime = followTime;
    }


    /**
     * get 跟进人
     *
     * @return
     */
    public String getFollowPerson() {
        return followPerson;
    }

    /**
     * set 跟进人
     *
     * @param followPerson
     */
    public void setFollowPerson(String followPerson) {
        this.followPerson = followPerson;
    }


    /**
     * get 跟进说明
     *
     * @return
     */
    public String getFollowRemark() {
        return followRemark;
    }

    /**
     * set 跟进说明
     *
     * @param followRemark
     */
    public void setFollowRemark(String followRemark) {
        this.followRemark = followRemark;
    }



    /**
    * set 合作线索列表
    *
    * @param applyDistributorList
    */
    public FollowApplyDistributorRequest applyDistributorList(List<ApplyDistributorDTO> applyDistributorList) {
        this.applyDistributorList = applyDistributorList;
        return this;
    }


    /**
     * set 状态
     *
     * @param status
     */
    public FollowApplyDistributorRequest status(Integer status) {
        this.status = status;
        return this;
    }


    /**
     * set 状态说明
     *
     * @param statusRemark
     */
    public FollowApplyDistributorRequest statusRemark(String statusRemark) {
        this.statusRemark = statusRemark;
        return this;
    }


    /**
     * set 跟进时间
     *
     * @param followTime
     */
    public FollowApplyDistributorRequest followTime(String followTime) {
        this.followTime = followTime;
        return this;
    }


    /**
     * set 跟进人
     *
     * @param followPerson
     */
    public FollowApplyDistributorRequest followPerson(String followPerson) {
        this.followPerson = followPerson;
        return this;
    }


    /**
     * set 跟进说明
     *
     * @param followRemark
     */
    public FollowApplyDistributorRequest followRemark(String followRemark) {
        this.followRemark = followRemark;
        return this;
    }



    /**
     * add item to 合作线索列表
     *
     * @param applyDistributorList
     */
    public void addApplyDistributorList(ApplyDistributorDTO applyDistributorList) {
        if (this.applyDistributorList == null) {
            this.applyDistributorList = new ArrayList<>();
        }
        this.applyDistributorList.add(applyDistributorList);
    }
}