/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * customer
 * 客户管理
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.partner.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.partner.model.PartnerUserDTO;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 查询渠道用户信息
 */
public class GetPartnerUserListResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * partnerUserDTOList
     */
    
    private List<PartnerUserDTO> partnerUserDTOList;


    /**
    * get partnerUserDTOList
    *
    * @return
    */
    public List<PartnerUserDTO> getPartnerUserDTOList() {
        return partnerUserDTOList;
    }

    /**
    * set partnerUserDTOList
    *
    * @param partnerUserDTOList
    */
    public void setPartnerUserDTOList(List<PartnerUserDTO> partnerUserDTOList) {
        this.partnerUserDTOList = partnerUserDTOList;
    }



    /**
    * set partnerUserDTOList
    *
    * @param partnerUserDTOList
    */
    public GetPartnerUserListResult partnerUserDTOList(List<PartnerUserDTO> partnerUserDTOList) {
        this.partnerUserDTOList = partnerUserDTOList;
        return this;
    }



    /**
     * add item to partnerUserDTOList
     *
     * @param partnerUserDTOList
     */
    public void addPartnerUserDTOList(PartnerUserDTO partnerUserDTOList) {
        if (this.partnerUserDTOList == null) {
            this.partnerUserDTOList = new ArrayList<>();
        }
        this.partnerUserDTOList.add(partnerUserDTOList);
    }
}