/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.partner.model;


/**
 * operateAuthorityQuery
 */
public class OperateAuthorityQuery  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * ID
     */
    private Number id;

    /**
     * 部门ID
     */
    private Integer deptId;

    /**
     * 部门名称
     */
    private String deptName;

    /**
     * 操作人
     */
    private String operator;

    /**
     * 修改时间
     */
    private String createTime;

    /**
     * 创建人
     */
    private String createUser;

    /**
     * 修改时间
     */
    private String updateTime;

    /**
     * 修改人
     */
    private String updateUser;

    /**
     * 是否删除0未删除,1已删除
     */
    private Integer yn;

    /**
     * 当前页序号
     */
    private Integer pageIndex;

    /**
     * 每页结果数量
     */
    private Integer pageSize;

    /**
     * offset
     */
    private Integer offset;


    /**
     * get ID
     *
     * @return
     */
    public Number getId() {
        return id;
    }

    /**
     * set ID
     *
     * @param id
     */
    public void setId(Number id) {
        this.id = id;
    }

    /**
     * get 部门ID
     *
     * @return
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * set 部门ID
     *
     * @param deptId
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * get 部门名称
     *
     * @return
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * set 部门名称
     *
     * @param deptName
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * get 操作人
     *
     * @return
     */
    public String getOperator() {
        return operator;
    }

    /**
     * set 操作人
     *
     * @param operator
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * get 修改时间
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 修改时间
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * get 创建人
     *
     * @return
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set 创建人
     *
     * @param createUser
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * get 修改时间
     *
     * @return
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * set 修改时间
     *
     * @param updateTime
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * get 修改人
     *
     * @return
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set 修改人
     *
     * @param updateUser
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * get 是否删除0未删除,1已删除
     *
     * @return
     */
    public Integer getYn() {
        return yn;
    }

    /**
     * set 是否删除0未删除,1已删除
     *
     * @param yn
     */
    public void setYn(Integer yn) {
        this.yn = yn;
    }

    /**
     * get 当前页序号
     *
     * @return
     */
    public Integer getPageIndex() {
        return pageIndex;
    }

    /**
     * set 当前页序号
     *
     * @param pageIndex
     */
    public void setPageIndex(Integer pageIndex) {
        this.pageIndex = pageIndex;
    }

    /**
     * get 每页结果数量
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set 每页结果数量
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * get offset
     *
     * @return
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * set offset
     *
     * @param offset
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }


    /**
     * set ID
     *
     * @param id
     */
    public OperateAuthorityQuery id(Number id) {
        this.id = id;
        return this;
    }

    /**
     * set 部门ID
     *
     * @param deptId
     */
    public OperateAuthorityQuery deptId(Integer deptId) {
        this.deptId = deptId;
        return this;
    }

    /**
     * set 部门名称
     *
     * @param deptName
     */
    public OperateAuthorityQuery deptName(String deptName) {
        this.deptName = deptName;
        return this;
    }

    /**
     * set 操作人
     *
     * @param operator
     */
    public OperateAuthorityQuery operator(String operator) {
        this.operator = operator;
        return this;
    }

    /**
     * set 修改时间
     *
     * @param createTime
     */
    public OperateAuthorityQuery createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * set 创建人
     *
     * @param createUser
     */
    public OperateAuthorityQuery createUser(String createUser) {
        this.createUser = createUser;
        return this;
    }

    /**
     * set 修改时间
     *
     * @param updateTime
     */
    public OperateAuthorityQuery updateTime(String updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * set 修改人
     *
     * @param updateUser
     */
    public OperateAuthorityQuery updateUser(String updateUser) {
        this.updateUser = updateUser;
        return this;
    }

    /**
     * set 是否删除0未删除,1已删除
     *
     * @param yn
     */
    public OperateAuthorityQuery yn(Integer yn) {
        this.yn = yn;
        return this;
    }

    /**
     * set 当前页序号
     *
     * @param pageIndex
     */
    public OperateAuthorityQuery pageIndex(Integer pageIndex) {
        this.pageIndex = pageIndex;
        return this;
    }

    /**
     * set 每页结果数量
     *
     * @param pageSize
     */
    public OperateAuthorityQuery pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * set offset
     *
     * @param offset
     */
    public OperateAuthorityQuery offset(Integer offset) {
        this.offset = offset;
        return this;
    }


}