/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.vpc.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.charge.model.ChargeSpec;

/**
 * azIpSpec
 */
public class AzIpSpec  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * IP线路类型，仅支持bgp，默认值bgp
     */
    private String provider;

    /**
     * 公网IP可用区属性
     * Required:true
     */
    @Required
    private String az;

    /**
     * NAT网关公网IP的限速（单位：Mbps）。计费类型为按配置时，取值范围为[1-1000]；计费类型为按流量时，取值范围为[1-200]
     * Required:true
     */
    @Required
    private Integer bandwidthMbps;

    /**
     * 计费配置,支持按配置、按用量，默认按配置
     */
    private ChargeSpec ipCharge;


    /**
     * get IP线路类型，仅支持bgp，默认值bgp
     *
     * @return
     */
    public String getProvider() {
        return provider;
    }

    /**
     * set IP线路类型，仅支持bgp，默认值bgp
     *
     * @param provider
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * get 公网IP可用区属性
     *
     * @return
     */
    public String getAz() {
        return az;
    }

    /**
     * set 公网IP可用区属性
     *
     * @param az
     */
    public void setAz(String az) {
        this.az = az;
    }

    /**
     * get NAT网关公网IP的限速（单位：Mbps）。计费类型为按配置时，取值范围为[1-1000]；计费类型为按流量时，取值范围为[1-200]
     *
     * @return
     */
    public Integer getBandwidthMbps() {
        return bandwidthMbps;
    }

    /**
     * set NAT网关公网IP的限速（单位：Mbps）。计费类型为按配置时，取值范围为[1-1000]；计费类型为按流量时，取值范围为[1-200]
     *
     * @param bandwidthMbps
     */
    public void setBandwidthMbps(Integer bandwidthMbps) {
        this.bandwidthMbps = bandwidthMbps;
    }

    /**
     * get 计费配置,支持按配置、按用量，默认按配置
     *
     * @return
     */
    public ChargeSpec getIpCharge() {
        return ipCharge;
    }

    /**
     * set 计费配置,支持按配置、按用量，默认按配置
     *
     * @param ipCharge
     */
    public void setIpCharge(ChargeSpec ipCharge) {
        this.ipCharge = ipCharge;
    }


    /**
     * set IP线路类型，仅支持bgp，默认值bgp
     *
     * @param provider
     */
    public AzIpSpec provider(String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * set 公网IP可用区属性
     *
     * @param az
     */
    public AzIpSpec az(String az) {
        this.az = az;
        return this;
    }

    /**
     * set NAT网关公网IP的限速（单位：Mbps）。计费类型为按配置时，取值范围为[1-1000]；计费类型为按流量时，取值范围为[1-200]
     *
     * @param bandwidthMbps
     */
    public AzIpSpec bandwidthMbps(Integer bandwidthMbps) {
        this.bandwidthMbps = bandwidthMbps;
        return this;
    }

    /**
     * set 计费配置,支持按配置、按用量，默认按配置
     *
     * @param ipCharge
     */
    public AzIpSpec ipCharge(ChargeSpec ipCharge) {
        this.ipCharge = ipCharge;
        return this;
    }


}