/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.domainservice.model;


/**
 * userview
 */
public class Userview  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 自定义线路ID
     */
    private Integer viewId;

    /**
     * 自定义线路名称, 最多64个字节，允许：数字、字母、下划线，-，中文
     */
    private String viewName;

    /**
     * 主域名ID
     */
    private Integer domainId;

    /**
     * 域名
     */
    private String domainName;

    /**
     * 是否删除，0:没有删除，1:已删除
     */
    private Integer isDelete;

    /**
     * 创建者
     */
    private String creator;

    /**
     * 创建时间，格式Unix timestamp，时间单位：秒
     */
    private Integer createTime;

    /**
     * 更新者
     */
    private String updator;

    /**
     * 更新时间，格式Unix timestamp，时间单位：秒
     */
    private Integer updateTime;


    /**
     * get 自定义线路ID
     *
     * @return
     */
    public Integer getViewId() {
        return viewId;
    }

    /**
     * set 自定义线路ID
     *
     * @param viewId
     */
    public void setViewId(Integer viewId) {
        this.viewId = viewId;
    }

    /**
     * get 自定义线路名称, 最多64个字节，允许：数字、字母、下划线，-，中文
     *
     * @return
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * set 自定义线路名称, 最多64个字节，允许：数字、字母、下划线，-，中文
     *
     * @param viewName
     */
    public void setViewName(String viewName) {
        this.viewName = viewName;
    }

    /**
     * get 主域名ID
     *
     * @return
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * set 主域名ID
     *
     * @param domainId
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * get 域名
     *
     * @return
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * set 域名
     *
     * @param domainName
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * get 是否删除，0:没有删除，1:已删除
     *
     * @return
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * set 是否删除，0:没有删除，1:已删除
     *
     * @param isDelete
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * get 创建者
     *
     * @return
     */
    public String getCreator() {
        return creator;
    }

    /**
     * set 创建者
     *
     * @param creator
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * get 创建时间，格式Unix timestamp，时间单位：秒
     *
     * @return
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * set 创建时间，格式Unix timestamp，时间单位：秒
     *
     * @param createTime
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * get 更新者
     *
     * @return
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * set 更新者
     *
     * @param updator
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * get 更新时间，格式Unix timestamp，时间单位：秒
     *
     * @return
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * set 更新时间，格式Unix timestamp，时间单位：秒
     *
     * @param updateTime
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }


    /**
     * set 自定义线路ID
     *
     * @param viewId
     */
    public Userview viewId(Integer viewId) {
        this.viewId = viewId;
        return this;
    }

    /**
     * set 自定义线路名称, 最多64个字节，允许：数字、字母、下划线，-，中文
     *
     * @param viewName
     */
    public Userview viewName(String viewName) {
        this.viewName = viewName;
        return this;
    }

    /**
     * set 主域名ID
     *
     * @param domainId
     */
    public Userview domainId(Integer domainId) {
        this.domainId = domainId;
        return this;
    }

    /**
     * set 域名
     *
     * @param domainName
     */
    public Userview domainName(String domainName) {
        this.domainName = domainName;
        return this;
    }

    /**
     * set 是否删除，0:没有删除，1:已删除
     *
     * @param isDelete
     */
    public Userview isDelete(Integer isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    /**
     * set 创建者
     *
     * @param creator
     */
    public Userview creator(String creator) {
        this.creator = creator;
        return this;
    }

    /**
     * set 创建时间，格式Unix timestamp，时间单位：秒
     *
     * @param createTime
     */
    public Userview createTime(Integer createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * set 更新者
     *
     * @param updator
     */
    public Userview updator(String updator) {
        this.updator = updator;
        return this;
    }

    /**
     * set 更新时间，格式Unix timestamp，时间单位：秒
     *
     * @param updateTime
     */
    public Userview updateTime(Integer updateTime) {
        this.updateTime = updateTime;
        return this;
    }


}