/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SplitItemBill APIs
 * 分账账单
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.billing.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 分账账单计费项明细分页查询
 */
public class DescribeSplitBillItemsRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 当前页序号
     */
    private Integer pageIndex;

    /**
     * 每页结果数量
     */
    private Integer pageSize;

    /**
     * 查询类型，1.按天，2.按月
     * Required:true
     */
    @Required
    private Integer queryType;

    /**
     * 开始查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     * Required:true
     */
    @Required
    private String billStartDate;

    /**
     * 结束查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     * Required:true
     */
    @Required
    private String billEndDate;

    /**
     * 产品
     */
    private String serviceCode;

    /**
     * 产品 List
     */
    
    private List<String> serviceCodes;
    /**
     * 地域
     */
    private String region;

    /**
     * 可用区
     */
    private String az;

    /**
     * 资源id
     */
    private String resourceId;

    /**
     * 分拆项id
     */
    private String subId;

    /**
     * 分拆项名称
     */
    private String subName;

    /**
     * 分拆项id List
     */
    
    private List<String> subIds;
    /**
     * 计费项key，精确匹配
     */
    private String billItem;

    /**
     * 标签
     */
    
    private List<Object> tags;
    /**
     * regionId
     * Required:true
     */
    @Required
    private String regionId;



    /**
     * get 当前页序号
     *
     * @return
     */
    public Integer getPageIndex() {
        return pageIndex;
    }

    /**
     * set 当前页序号
     *
     * @param pageIndex
     */
    public void setPageIndex(Integer pageIndex) {
        this.pageIndex = pageIndex;
    }


    /**
     * get 每页结果数量
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set 每页结果数量
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }


    /**
     * get 查询类型，1.按天，2.按月
     *
     * @return
     */
    public Integer getQueryType() {
        return queryType;
    }

    /**
     * set 查询类型，1.按天，2.按月
     *
     * @param queryType
     */
    public void setQueryType(Integer queryType) {
        this.queryType = queryType;
    }


    /**
     * get 开始查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @return
     */
    public String getBillStartDate() {
        return billStartDate;
    }

    /**
     * set 开始查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @param billStartDate
     */
    public void setBillStartDate(String billStartDate) {
        this.billStartDate = billStartDate;
    }


    /**
     * get 结束查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @return
     */
    public String getBillEndDate() {
        return billEndDate;
    }

    /**
     * set 结束查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @param billEndDate
     */
    public void setBillEndDate(String billEndDate) {
        this.billEndDate = billEndDate;
    }


    /**
     * get 产品
     *
     * @return
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * set 产品
     *
     * @param serviceCode
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }


    /**
    * get 产品 List
    *
    * @return
    */
    public List<String> getServiceCodes() {
        return serviceCodes;
    }

    /**
    * set 产品 List
    *
    * @param serviceCodes
    */
    public void setServiceCodes(List<String> serviceCodes) {
        this.serviceCodes = serviceCodes;
    }


    /**
     * get 地域
     *
     * @return
     */
    public String getRegion() {
        return region;
    }

    /**
     * set 地域
     *
     * @param region
     */
    public void setRegion(String region) {
        this.region = region;
    }


    /**
     * get 可用区
     *
     * @return
     */
    public String getAz() {
        return az;
    }

    /**
     * set 可用区
     *
     * @param az
     */
    public void setAz(String az) {
        this.az = az;
    }


    /**
     * get 资源id
     *
     * @return
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * set 资源id
     *
     * @param resourceId
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }


    /**
     * get 分拆项id
     *
     * @return
     */
    public String getSubId() {
        return subId;
    }

    /**
     * set 分拆项id
     *
     * @param subId
     */
    public void setSubId(String subId) {
        this.subId = subId;
    }


    /**
     * get 分拆项名称
     *
     * @return
     */
    public String getSubName() {
        return subName;
    }

    /**
     * set 分拆项名称
     *
     * @param subName
     */
    public void setSubName(String subName) {
        this.subName = subName;
    }


    /**
    * get 分拆项id List
    *
    * @return
    */
    public List<String> getSubIds() {
        return subIds;
    }

    /**
    * set 分拆项id List
    *
    * @param subIds
    */
    public void setSubIds(List<String> subIds) {
        this.subIds = subIds;
    }


    /**
     * get 计费项key，精确匹配
     *
     * @return
     */
    public String getBillItem() {
        return billItem;
    }

    /**
     * set 计费项key，精确匹配
     *
     * @param billItem
     */
    public void setBillItem(String billItem) {
        this.billItem = billItem;
    }


    /**
    * get 标签
    *
    * @return
    */
    public List<Object> getTags() {
        return tags;
    }

    /**
    * set 标签
    *
    * @param tags
    */
    public void setTags(List<Object> tags) {
        this.tags = tags;
    }


    /**
     * get regionId
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set regionId
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }



    /**
     * set 当前页序号
     *
     * @param pageIndex
     */
    public DescribeSplitBillItemsRequest pageIndex(Integer pageIndex) {
        this.pageIndex = pageIndex;
        return this;
    }


    /**
     * set 每页结果数量
     *
     * @param pageSize
     */
    public DescribeSplitBillItemsRequest pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }


    /**
     * set 查询类型，1.按天，2.按月
     *
     * @param queryType
     */
    public DescribeSplitBillItemsRequest queryType(Integer queryType) {
        this.queryType = queryType;
        return this;
    }


    /**
     * set 开始查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @param billStartDate
     */
    public DescribeSplitBillItemsRequest billStartDate(String billStartDate) {
        this.billStartDate = billStartDate;
        return this;
    }


    /**
     * set 结束查询账期，按月：yyyy-MM，按天：yyyy-MM-dd
     *
     * @param billEndDate
     */
    public DescribeSplitBillItemsRequest billEndDate(String billEndDate) {
        this.billEndDate = billEndDate;
        return this;
    }


    /**
     * set 产品
     *
     * @param serviceCode
     */
    public DescribeSplitBillItemsRequest serviceCode(String serviceCode) {
        this.serviceCode = serviceCode;
        return this;
    }


    /**
    * set 产品 List
    *
    * @param serviceCodes
    */
    public DescribeSplitBillItemsRequest serviceCodes(List<String> serviceCodes) {
        this.serviceCodes = serviceCodes;
        return this;
    }


    /**
     * set 地域
     *
     * @param region
     */
    public DescribeSplitBillItemsRequest region(String region) {
        this.region = region;
        return this;
    }


    /**
     * set 可用区
     *
     * @param az
     */
    public DescribeSplitBillItemsRequest az(String az) {
        this.az = az;
        return this;
    }


    /**
     * set 资源id
     *
     * @param resourceId
     */
    public DescribeSplitBillItemsRequest resourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }


    /**
     * set 分拆项id
     *
     * @param subId
     */
    public DescribeSplitBillItemsRequest subId(String subId) {
        this.subId = subId;
        return this;
    }


    /**
     * set 分拆项名称
     *
     * @param subName
     */
    public DescribeSplitBillItemsRequest subName(String subName) {
        this.subName = subName;
        return this;
    }


    /**
    * set 分拆项id List
    *
    * @param subIds
    */
    public DescribeSplitBillItemsRequest subIds(List<String> subIds) {
        this.subIds = subIds;
        return this;
    }


    /**
     * set 计费项key，精确匹配
     *
     * @param billItem
     */
    public DescribeSplitBillItemsRequest billItem(String billItem) {
        this.billItem = billItem;
        return this;
    }


    /**
    * set 标签
    *
    * @param tags
    */
    public DescribeSplitBillItemsRequest tags(List<Object> tags) {
        this.tags = tags;
        return this;
    }


    /**
     * set regionId
     *
     * @param regionId
     */
    public DescribeSplitBillItemsRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }



    /**
     * add item to 产品 List
     *
     * @param serviceCode
     */
    public void addServiceCode(String serviceCode) {
        if (this.serviceCodes == null) {
            this.serviceCodes = new ArrayList<>();
        }
        this.serviceCodes.add(serviceCode);
    }

    /**
     * add item to 分拆项id List
     *
     * @param subId
     */
    public void addSubId(String subId) {
        if (this.subIds == null) {
            this.subIds = new ArrayList<>();
        }
        this.subIds.add(subId);
    }

    /**
     * add item to 标签
     *
     * @param tag
     */
    public void addTag(Object tag) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tag);
    }
}