/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.billing.model;

import java.util.List;
import java.util.ArrayList;

/**
 * splitItemBillSummary
 */
public class SplitItemBillSummary  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 账期
     */
    private String billDate;

    /**
     * 账单生成时间，仅用于查询分账账单天汇总接口
     */
    private String billTime;

    /**
     * 用户pin
     */
    private String pin;

    /**
     * 产品线代码
     */
    private String appCode;

    /**
     * 产品线代码名称
     */
    private String appCodeName;

    /**
     * 产品代码
     */
    private String serviceCode;

    /**
     * 产品代码名称
     */
    private String serviceCodeName;

    /**
     * 计费类型
     */
    private Integer billingType;

    /**
     * 计费类型描述
     */
    private String billingTypeName;

    /**
     * 账单编号，仅用于查询分账账单天汇总接口
     */
    private String billId;

    /**
     * 资源id
     */
    private String resourceId;

    /**
     * 区域
     */
    private String region;

    /**
     * 可用区
     */
    private String az;

    /**
     * 分拆项ID
     */
    private String subId;

    /**
     * 分拆项名称
     */
    private String subName;

    /**
     * 计费项信息
     */
    private String formulaInfo;

    /**
     * 用量信息
     */
    private String usageInfo;

    /**
     * 单价
     */
    private String unitPriceInfo;

    /**
     * 资源包抵扣
     */
    private String deductUsageInfo;

    /**
     * 原价
     */
    private Double billFee;

    /**
     * 应付金额
     */
    private Double actualFee;

    /**
     * 标签明细
     */
    
    private List<ResourceTagVo> tagDetails;


    /**
     * get 账期
     *
     * @return
     */
    public String getBillDate() {
        return billDate;
    }

    /**
     * set 账期
     *
     * @param billDate
     */
    public void setBillDate(String billDate) {
        this.billDate = billDate;
    }


    /**
     * get 账单生成时间，仅用于查询分账账单天汇总接口
     *
     * @return
     */
    public String getBillTime() {
        return billTime;
    }

    /**
     * set 账单生成时间，仅用于查询分账账单天汇总接口
     *
     * @param billTime
     */
    public void setBillTime(String billTime) {
        this.billTime = billTime;
    }


    /**
     * get 用户pin
     *
     * @return
     */
    public String getPin() {
        return pin;
    }

    /**
     * set 用户pin
     *
     * @param pin
     */
    public void setPin(String pin) {
        this.pin = pin;
    }


    /**
     * get 产品线代码
     *
     * @return
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * set 产品线代码
     *
     * @param appCode
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }


    /**
     * get 产品线代码名称
     *
     * @return
     */
    public String getAppCodeName() {
        return appCodeName;
    }

    /**
     * set 产品线代码名称
     *
     * @param appCodeName
     */
    public void setAppCodeName(String appCodeName) {
        this.appCodeName = appCodeName;
    }


    /**
     * get 产品代码
     *
     * @return
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * set 产品代码
     *
     * @param serviceCode
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }


    /**
     * get 产品代码名称
     *
     * @return
     */
    public String getServiceCodeName() {
        return serviceCodeName;
    }

    /**
     * set 产品代码名称
     *
     * @param serviceCodeName
     */
    public void setServiceCodeName(String serviceCodeName) {
        this.serviceCodeName = serviceCodeName;
    }


    /**
     * get 计费类型
     *
     * @return
     */
    public Integer getBillingType() {
        return billingType;
    }

    /**
     * set 计费类型
     *
     * @param billingType
     */
    public void setBillingType(Integer billingType) {
        this.billingType = billingType;
    }


    /**
     * get 计费类型描述
     *
     * @return
     */
    public String getBillingTypeName() {
        return billingTypeName;
    }

    /**
     * set 计费类型描述
     *
     * @param billingTypeName
     */
    public void setBillingTypeName(String billingTypeName) {
        this.billingTypeName = billingTypeName;
    }


    /**
     * get 账单编号，仅用于查询分账账单天汇总接口
     *
     * @return
     */
    public String getBillId() {
        return billId;
    }

    /**
     * set 账单编号，仅用于查询分账账单天汇总接口
     *
     * @param billId
     */
    public void setBillId(String billId) {
        this.billId = billId;
    }


    /**
     * get 资源id
     *
     * @return
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * set 资源id
     *
     * @param resourceId
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }


    /**
     * get 区域
     *
     * @return
     */
    public String getRegion() {
        return region;
    }

    /**
     * set 区域
     *
     * @param region
     */
    public void setRegion(String region) {
        this.region = region;
    }


    /**
     * get 可用区
     *
     * @return
     */
    public String getAz() {
        return az;
    }

    /**
     * set 可用区
     *
     * @param az
     */
    public void setAz(String az) {
        this.az = az;
    }


    /**
     * get 分拆项ID
     *
     * @return
     */
    public String getSubId() {
        return subId;
    }

    /**
     * set 分拆项ID
     *
     * @param subId
     */
    public void setSubId(String subId) {
        this.subId = subId;
    }


    /**
     * get 分拆项名称
     *
     * @return
     */
    public String getSubName() {
        return subName;
    }

    /**
     * set 分拆项名称
     *
     * @param subName
     */
    public void setSubName(String subName) {
        this.subName = subName;
    }


    /**
     * get 计费项信息
     *
     * @return
     */
    public String getFormulaInfo() {
        return formulaInfo;
    }

    /**
     * set 计费项信息
     *
     * @param formulaInfo
     */
    public void setFormulaInfo(String formulaInfo) {
        this.formulaInfo = formulaInfo;
    }


    /**
     * get 用量信息
     *
     * @return
     */
    public String getUsageInfo() {
        return usageInfo;
    }

    /**
     * set 用量信息
     *
     * @param usageInfo
     */
    public void setUsageInfo(String usageInfo) {
        this.usageInfo = usageInfo;
    }


    /**
     * get 单价
     *
     * @return
     */
    public String getUnitPriceInfo() {
        return unitPriceInfo;
    }

    /**
     * set 单价
     *
     * @param unitPriceInfo
     */
    public void setUnitPriceInfo(String unitPriceInfo) {
        this.unitPriceInfo = unitPriceInfo;
    }


    /**
     * get 资源包抵扣
     *
     * @return
     */
    public String getDeductUsageInfo() {
        return deductUsageInfo;
    }

    /**
     * set 资源包抵扣
     *
     * @param deductUsageInfo
     */
    public void setDeductUsageInfo(String deductUsageInfo) {
        this.deductUsageInfo = deductUsageInfo;
    }


    /**
     * get 原价
     *
     * @return
     */
    public Double getBillFee() {
        return billFee;
    }

    /**
     * set 原价
     *
     * @param billFee
     */
    public void setBillFee(Double billFee) {
        this.billFee = billFee;
    }


    /**
     * get 应付金额
     *
     * @return
     */
    public Double getActualFee() {
        return actualFee;
    }

    /**
     * set 应付金额
     *
     * @param actualFee
     */
    public void setActualFee(Double actualFee) {
        this.actualFee = actualFee;
    }


    /**
    * get 标签明细
    *
    * @return
    */
    public List<ResourceTagVo> getTagDetails() {
        return tagDetails;
    }

    /**
    * set 标签明细
    *
    * @param tagDetails
    */
    public void setTagDetails(List<ResourceTagVo> tagDetails) {
        this.tagDetails = tagDetails;
    }



    /**
     * set 账期
     *
     * @param billDate
     */
    public SplitItemBillSummary billDate(String billDate) {
        this.billDate = billDate;
        return this;
    }


    /**
     * set 账单生成时间，仅用于查询分账账单天汇总接口
     *
     * @param billTime
     */
    public SplitItemBillSummary billTime(String billTime) {
        this.billTime = billTime;
        return this;
    }


    /**
     * set 用户pin
     *
     * @param pin
     */
    public SplitItemBillSummary pin(String pin) {
        this.pin = pin;
        return this;
    }


    /**
     * set 产品线代码
     *
     * @param appCode
     */
    public SplitItemBillSummary appCode(String appCode) {
        this.appCode = appCode;
        return this;
    }


    /**
     * set 产品线代码名称
     *
     * @param appCodeName
     */
    public SplitItemBillSummary appCodeName(String appCodeName) {
        this.appCodeName = appCodeName;
        return this;
    }


    /**
     * set 产品代码
     *
     * @param serviceCode
     */
    public SplitItemBillSummary serviceCode(String serviceCode) {
        this.serviceCode = serviceCode;
        return this;
    }


    /**
     * set 产品代码名称
     *
     * @param serviceCodeName
     */
    public SplitItemBillSummary serviceCodeName(String serviceCodeName) {
        this.serviceCodeName = serviceCodeName;
        return this;
    }


    /**
     * set 计费类型
     *
     * @param billingType
     */
    public SplitItemBillSummary billingType(Integer billingType) {
        this.billingType = billingType;
        return this;
    }


    /**
     * set 计费类型描述
     *
     * @param billingTypeName
     */
    public SplitItemBillSummary billingTypeName(String billingTypeName) {
        this.billingTypeName = billingTypeName;
        return this;
    }


    /**
     * set 账单编号，仅用于查询分账账单天汇总接口
     *
     * @param billId
     */
    public SplitItemBillSummary billId(String billId) {
        this.billId = billId;
        return this;
    }


    /**
     * set 资源id
     *
     * @param resourceId
     */
    public SplitItemBillSummary resourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }


    /**
     * set 区域
     *
     * @param region
     */
    public SplitItemBillSummary region(String region) {
        this.region = region;
        return this;
    }


    /**
     * set 可用区
     *
     * @param az
     */
    public SplitItemBillSummary az(String az) {
        this.az = az;
        return this;
    }


    /**
     * set 分拆项ID
     *
     * @param subId
     */
    public SplitItemBillSummary subId(String subId) {
        this.subId = subId;
        return this;
    }


    /**
     * set 分拆项名称
     *
     * @param subName
     */
    public SplitItemBillSummary subName(String subName) {
        this.subName = subName;
        return this;
    }


    /**
     * set 计费项信息
     *
     * @param formulaInfo
     */
    public SplitItemBillSummary formulaInfo(String formulaInfo) {
        this.formulaInfo = formulaInfo;
        return this;
    }


    /**
     * set 用量信息
     *
     * @param usageInfo
     */
    public SplitItemBillSummary usageInfo(String usageInfo) {
        this.usageInfo = usageInfo;
        return this;
    }


    /**
     * set 单价
     *
     * @param unitPriceInfo
     */
    public SplitItemBillSummary unitPriceInfo(String unitPriceInfo) {
        this.unitPriceInfo = unitPriceInfo;
        return this;
    }


    /**
     * set 资源包抵扣
     *
     * @param deductUsageInfo
     */
    public SplitItemBillSummary deductUsageInfo(String deductUsageInfo) {
        this.deductUsageInfo = deductUsageInfo;
        return this;
    }


    /**
     * set 原价
     *
     * @param billFee
     */
    public SplitItemBillSummary billFee(Double billFee) {
        this.billFee = billFee;
        return this;
    }


    /**
     * set 应付金额
     *
     * @param actualFee
     */
    public SplitItemBillSummary actualFee(Double actualFee) {
        this.actualFee = actualFee;
        return this;
    }


    /**
    * set 标签明细
    *
    * @param tagDetails
    */
    public SplitItemBillSummary tagDetails(List<ResourceTagVo> tagDetails) {
        this.tagDetails = tagDetails;
        return this;
    }



    /**
     * add item to 标签明细
     *
     * @param tagDetail
     */
    public void addTagDetail(ResourceTagVo tagDetail) {
        if (this.tagDetails == null) {
            this.tagDetails = new ArrayList<>();
        }
        this.tagDetails.add(tagDetail);
    }
}