/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.dbaudit.model;


/**
 * ruleAbstract
 */
public class RuleAbstract  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 规则ID
     */
    private String ruleId;

    /**
     * 规则名称，长度限制32字节
     */
    private String ruleName;


    /**
     * get 规则ID
     *
     * @return
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * set 规则ID
     *
     * @param ruleId
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * get 规则名称，长度限制32字节
     *
     * @return
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * set 规则名称，长度限制32字节
     *
     * @param ruleName
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }


    /**
     * set 规则ID
     *
     * @param ruleId
     */
    public RuleAbstract ruleId(String ruleId) {
        this.ruleId = ruleId;
        return this;
    }

    /**
     * set 规则名称，长度限制32字节
     *
     * @param ruleName
     */
    public RuleAbstract ruleName(String ruleName) {
        this.ruleName = ruleName;
        return this;
    }


}