/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.aifactory.model;


/**
 * Spark Executor配置
 */
public class AiOpsRayTaskInstanceSparkExecutorConfig  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * CPU核数
     */
    private Integer cores;

    /**
     * 内存大小（GB）
     */
    private Integer memory;

    /**
     * GPU（卡）
     */
    private Integer gpu;

    /**
     * GPU名称
     */
    private String gpuName;

    /**
     * 实例数
     */
    private Integer instances;



    /**
     * get CPU核数
     *
     * @return
     */
    public Integer getCores() {
        return cores;
    }

    /**
     * set CPU核数
     *
     * @param cores
     */
    public void setCores(Integer cores) {
        this.cores = cores;
    }


    /**
     * get 内存大小（GB）
     *
     * @return
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * set 内存大小（GB）
     *
     * @param memory
     */
    public void setMemory(Integer memory) {
        this.memory = memory;
    }


    /**
     * get GPU（卡）
     *
     * @return
     */
    public Integer getGpu() {
        return gpu;
    }

    /**
     * set GPU（卡）
     *
     * @param gpu
     */
    public void setGpu(Integer gpu) {
        this.gpu = gpu;
    }


    /**
     * get GPU名称
     *
     * @return
     */
    public String getGpuName() {
        return gpuName;
    }

    /**
     * set GPU名称
     *
     * @param gpuName
     */
    public void setGpuName(String gpuName) {
        this.gpuName = gpuName;
    }


    /**
     * get 实例数
     *
     * @return
     */
    public Integer getInstances() {
        return instances;
    }

    /**
     * set 实例数
     *
     * @param instances
     */
    public void setInstances(Integer instances) {
        this.instances = instances;
    }



    /**
     * set CPU核数
     *
     * @param cores CPU核数
     * @return AiOpsRayTaskInstanceSparkExecutorConfig
     */
    public AiOpsRayTaskInstanceSparkExecutorConfig cores(Integer cores) {
        this.cores = cores;
        return this;
    }


    /**
     * set 内存大小（GB）
     *
     * @param memory 内存大小（GB）
     * @return AiOpsRayTaskInstanceSparkExecutorConfig
     */
    public AiOpsRayTaskInstanceSparkExecutorConfig memory(Integer memory) {
        this.memory = memory;
        return this;
    }


    /**
     * set GPU（卡）
     *
     * @param gpu GPU（卡）
     * @return AiOpsRayTaskInstanceSparkExecutorConfig
     */
    public AiOpsRayTaskInstanceSparkExecutorConfig gpu(Integer gpu) {
        this.gpu = gpu;
        return this;
    }


    /**
     * set GPU名称
     *
     * @param gpuName GPU名称
     * @return AiOpsRayTaskInstanceSparkExecutorConfig
     */
    public AiOpsRayTaskInstanceSparkExecutorConfig gpuName(String gpuName) {
        this.gpuName = gpuName;
        return this;
    }


    /**
     * set 实例数
     *
     * @param instances 实例数
     * @return AiOpsRayTaskInstanceSparkExecutorConfig
     */
    public AiOpsRayTaskInstanceSparkExecutorConfig instances(Integer instances) {
        this.instances = instances;
        return this;
    }


}