/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.aifactory.model;


/**
 * 镜像构建任务信息
 */
public class ImageBuildTaskVO  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 区域ID
     */
    private String regionId;

    /**
     * 公司编码
     */
    private String companyCode;

    /**
     * 工作空间编码
     */
    private String workspaceCode;

    /**
     * 镜像ID
     */
    private String imageId;

    /**
     * 镜像名称
     */
    private String imageName;

    /**
     * 镜像版本
     */
    private String imageVersion;

    /**
     * 镜像大小
     */
    private String imageSize;

    /**
     * 镜像描述
     */
    private String imageDescription;

    /**
     * 镜像创建时间
     */
    private String imageCreateTime;

    /**
     * 镜像更新时间
     */
    private String imageUpdateTime;

    /**
     * 构建类型
     */
    private String buildType;

    /**
     * 版本描述
     */
    private String versionDescription;

    /**
     * 构建任务ID
     */
    private String buildId;

    /**
     * 构建状态
     */
    private String buildStatus;

    /**
     * 任务创建时间
     */
    private String createTime;

    /**
     * 创建人
     */
    private String creator;



    /**
     * get 区域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 区域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 公司编码
     *
     * @return
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * set 公司编码
     *
     * @param companyCode
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }


    /**
     * get 工作空间编码
     *
     * @return
     */
    public String getWorkspaceCode() {
        return workspaceCode;
    }

    /**
     * set 工作空间编码
     *
     * @param workspaceCode
     */
    public void setWorkspaceCode(String workspaceCode) {
        this.workspaceCode = workspaceCode;
    }


    /**
     * get 镜像ID
     *
     * @return
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * set 镜像ID
     *
     * @param imageId
     */
    public void setImageId(String imageId) {
        this.imageId = imageId;
    }


    /**
     * get 镜像名称
     *
     * @return
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * set 镜像名称
     *
     * @param imageName
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }


    /**
     * get 镜像版本
     *
     * @return
     */
    public String getImageVersion() {
        return imageVersion;
    }

    /**
     * set 镜像版本
     *
     * @param imageVersion
     */
    public void setImageVersion(String imageVersion) {
        this.imageVersion = imageVersion;
    }


    /**
     * get 镜像大小
     *
     * @return
     */
    public String getImageSize() {
        return imageSize;
    }

    /**
     * set 镜像大小
     *
     * @param imageSize
     */
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize;
    }


    /**
     * get 镜像描述
     *
     * @return
     */
    public String getImageDescription() {
        return imageDescription;
    }

    /**
     * set 镜像描述
     *
     * @param imageDescription
     */
    public void setImageDescription(String imageDescription) {
        this.imageDescription = imageDescription;
    }


    /**
     * get 镜像创建时间
     *
     * @return
     */
    public String getImageCreateTime() {
        return imageCreateTime;
    }

    /**
     * set 镜像创建时间
     *
     * @param imageCreateTime
     */
    public void setImageCreateTime(String imageCreateTime) {
        this.imageCreateTime = imageCreateTime;
    }


    /**
     * get 镜像更新时间
     *
     * @return
     */
    public String getImageUpdateTime() {
        return imageUpdateTime;
    }

    /**
     * set 镜像更新时间
     *
     * @param imageUpdateTime
     */
    public void setImageUpdateTime(String imageUpdateTime) {
        this.imageUpdateTime = imageUpdateTime;
    }


    /**
     * get 构建类型
     *
     * @return
     */
    public String getBuildType() {
        return buildType;
    }

    /**
     * set 构建类型
     *
     * @param buildType
     */
    public void setBuildType(String buildType) {
        this.buildType = buildType;
    }


    /**
     * get 版本描述
     *
     * @return
     */
    public String getVersionDescription() {
        return versionDescription;
    }

    /**
     * set 版本描述
     *
     * @param versionDescription
     */
    public void setVersionDescription(String versionDescription) {
        this.versionDescription = versionDescription;
    }


    /**
     * get 构建任务ID
     *
     * @return
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * set 构建任务ID
     *
     * @param buildId
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }


    /**
     * get 构建状态
     *
     * @return
     */
    public String getBuildStatus() {
        return buildStatus;
    }

    /**
     * set 构建状态
     *
     * @param buildStatus
     */
    public void setBuildStatus(String buildStatus) {
        this.buildStatus = buildStatus;
    }


    /**
     * get 任务创建时间
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 任务创建时间
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }


    /**
     * get 创建人
     *
     * @return
     */
    public String getCreator() {
        return creator;
    }

    /**
     * set 创建人
     *
     * @param creator
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }



    /**
     * set 区域ID
     *
     * @param regionId 区域ID
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 公司编码
     *
     * @param companyCode 公司编码
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO companyCode(String companyCode) {
        this.companyCode = companyCode;
        return this;
    }


    /**
     * set 工作空间编码
     *
     * @param workspaceCode 工作空间编码
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO workspaceCode(String workspaceCode) {
        this.workspaceCode = workspaceCode;
        return this;
    }


    /**
     * set 镜像ID
     *
     * @param imageId 镜像ID
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageId(String imageId) {
        this.imageId = imageId;
        return this;
    }


    /**
     * set 镜像名称
     *
     * @param imageName 镜像名称
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageName(String imageName) {
        this.imageName = imageName;
        return this;
    }


    /**
     * set 镜像版本
     *
     * @param imageVersion 镜像版本
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageVersion(String imageVersion) {
        this.imageVersion = imageVersion;
        return this;
    }


    /**
     * set 镜像大小
     *
     * @param imageSize 镜像大小
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageSize(String imageSize) {
        this.imageSize = imageSize;
        return this;
    }


    /**
     * set 镜像描述
     *
     * @param imageDescription 镜像描述
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageDescription(String imageDescription) {
        this.imageDescription = imageDescription;
        return this;
    }


    /**
     * set 镜像创建时间
     *
     * @param imageCreateTime 镜像创建时间
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageCreateTime(String imageCreateTime) {
        this.imageCreateTime = imageCreateTime;
        return this;
    }


    /**
     * set 镜像更新时间
     *
     * @param imageUpdateTime 镜像更新时间
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO imageUpdateTime(String imageUpdateTime) {
        this.imageUpdateTime = imageUpdateTime;
        return this;
    }


    /**
     * set 构建类型
     *
     * @param buildType 构建类型
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO buildType(String buildType) {
        this.buildType = buildType;
        return this;
    }


    /**
     * set 版本描述
     *
     * @param versionDescription 版本描述
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO versionDescription(String versionDescription) {
        this.versionDescription = versionDescription;
        return this;
    }


    /**
     * set 构建任务ID
     *
     * @param buildId 构建任务ID
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }


    /**
     * set 构建状态
     *
     * @param buildStatus 构建状态
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO buildStatus(String buildStatus) {
        this.buildStatus = buildStatus;
        return this;
    }


    /**
     * set 任务创建时间
     *
     * @param createTime 任务创建时间
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }


    /**
     * set 创建人
     *
     * @param creator 创建人
     * @return ImageBuildTaskVO
     */
    public ImageBuildTaskVO creator(String creator) {
        this.creator = creator;
        return this;
    }


}