/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.aifactory.model;


/**
 * listTagsForObjectParam
 */
public class ListTagsForObjectParam  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 资源类型：CATALOG/SCHEMA/TABLE/FILESET/MODEL/COLUMN
     */
    private String resourceType;

    /**
     * Catalog名称
     */
    private String catalogName;

    /**
     * Schema名称
     */
    private String schemaName;

    /**
     * 资源对象名称
     */
    private String objectName;

    /**
     * 列名称（仅COLUMN类型时必填）
     */
    private String columnName;



    /**
     * get 资源类型：CATALOG/SCHEMA/TABLE/FILESET/MODEL/COLUMN
     *
     * @return
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * set 资源类型：CATALOG/SCHEMA/TABLE/FILESET/MODEL/COLUMN
     *
     * @param resourceType
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }


    /**
     * get Catalog名称
     *
     * @return
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * set Catalog名称
     *
     * @param catalogName
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }


    /**
     * get Schema名称
     *
     * @return
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * set Schema名称
     *
     * @param schemaName
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }


    /**
     * get 资源对象名称
     *
     * @return
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * set 资源对象名称
     *
     * @param objectName
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }


    /**
     * get 列名称（仅COLUMN类型时必填）
     *
     * @return
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * set 列名称（仅COLUMN类型时必填）
     *
     * @param columnName
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }



    /**
     * set 资源类型：CATALOG/SCHEMA/TABLE/FILESET/MODEL/COLUMN
     *
     * @param resourceType 资源类型：CATALOG/SCHEMA/TABLE/FILESET/MODEL/COLUMN
     * @return ListTagsForObjectParam
     */
    public ListTagsForObjectParam resourceType(String resourceType) {
        this.resourceType = resourceType;
        return this;
    }


    /**
     * set Catalog名称
     *
     * @param catalogName Catalog名称
     * @return ListTagsForObjectParam
     */
    public ListTagsForObjectParam catalogName(String catalogName) {
        this.catalogName = catalogName;
        return this;
    }


    /**
     * set Schema名称
     *
     * @param schemaName Schema名称
     * @return ListTagsForObjectParam
     */
    public ListTagsForObjectParam schemaName(String schemaName) {
        this.schemaName = schemaName;
        return this;
    }


    /**
     * set 资源对象名称
     *
     * @param objectName 资源对象名称
     * @return ListTagsForObjectParam
     */
    public ListTagsForObjectParam objectName(String objectName) {
        this.objectName = objectName;
        return this;
    }


    /**
     * set 列名称（仅COLUMN类型时必填）
     *
     * @param columnName 列名称（仅COLUMN类型时必填）
     * @return ListTagsForObjectParam
     */
    public ListTagsForObjectParam columnName(String columnName) {
        this.columnName = columnName;
        return this;
    }


}