/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.aifactory.model;


/**
 * userDetailVo
 */
public class UserDetailVo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 用户pin
     */
    private String pin;

    /**
     * 用户名
     */
    private String name;

    /**
     * 用户登录Token
     */
    private String token;



    /**
     * get 用户pin
     *
     * @return
     */
    public String getPin() {
        return pin;
    }

    /**
     * set 用户pin
     *
     * @param pin
     */
    public void setPin(String pin) {
        this.pin = pin;
    }


    /**
     * get 用户名
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     * set 用户名
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * get 用户登录Token
     *
     * @return
     */
    public String getToken() {
        return token;
    }

    /**
     * set 用户登录Token
     *
     * @param token
     */
    public void setToken(String token) {
        this.token = token;
    }



    /**
     * set 用户pin
     *
     * @param pin 用户pin
     * @return UserDetailVo
     */
    public UserDetailVo pin(String pin) {
        this.pin = pin;
        return this;
    }


    /**
     * set 用户名
     *
     * @param name 用户名
     * @return UserDetailVo
     */
    public UserDetailVo name(String name) {
        this.name = name;
        return this;
    }


    /**
     * set 用户登录Token
     *
     * @param token 用户登录Token
     * @return UserDetailVo
     */
    public UserDetailVo token(String token) {
        this.token = token;
        return this;
    }


}