/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.bastion.model;

import com.jdcloud.sdk.annotation.Required;

/**
 * enableBastion
 */
public class EnableBastion  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 启用/停用 1/0
     * Required:true
     */
    @Required
    private Integer enable;



    /**
     * get 启用/停用 1/0
     *
     * @return
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * set 启用/停用 1/0
     *
     * @param enable
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }



    /**
     * set 启用/停用 1/0
     *
     * @param enable
     */
    public EnableBastion enable(Integer enable) {
        this.enable = enable;
        return this;
    }


}