/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.bri.model;


/**
 * bwcfg
 */
public class Bwcfg  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 数据的id，更新数据时需要传此ID
     */
    private Integer id;

    /**
     * 关联内容
     */
    private String content;

    /**
     * 黑白名单类型，黑名单-black，白名单-white
     */
    private String bwType;

    /**
     * 数据类型，ip-IP，phone-手机，addr-地址，card-身份，pin-账户，eid-设备
     */
    private String resourceType;


    /**
     * get 数据的id，更新数据时需要传此ID
     *
     * @return
     */
    public Integer getId() {
        return id;
    }

    /**
     * set 数据的id，更新数据时需要传此ID
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get 关联内容
     *
     * @return
     */
    public String getContent() {
        return content;
    }

    /**
     * set 关联内容
     *
     * @param content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * get 黑白名单类型，黑名单-black，白名单-white
     *
     * @return
     */
    public String getBwType() {
        return bwType;
    }

    /**
     * set 黑白名单类型，黑名单-black，白名单-white
     *
     * @param bwType
     */
    public void setBwType(String bwType) {
        this.bwType = bwType;
    }

    /**
     * get 数据类型，ip-IP，phone-手机，addr-地址，card-身份，pin-账户，eid-设备
     *
     * @return
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * set 数据类型，ip-IP，phone-手机，addr-地址，card-身份，pin-账户，eid-设备
     *
     * @param resourceType
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }


    /**
     * set 数据的id，更新数据时需要传此ID
     *
     * @param id
     */
    public Bwcfg id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * set 关联内容
     *
     * @param content
     */
    public Bwcfg content(String content) {
        this.content = content;
        return this;
    }

    /**
     * set 黑白名单类型，黑名单-black，白名单-white
     *
     * @param bwType
     */
    public Bwcfg bwType(String bwType) {
        this.bwType = bwType;
        return this;
    }

    /**
     * set 数据类型，ip-IP，phone-手机，addr-地址，card-身份，pin-账户，eid-设备
     *
     * @param resourceType
     */
    public Bwcfg resourceType(String resourceType) {
        this.resourceType = resourceType;
        return this;
    }


}