/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * JDCLOUD quota API
 * API JDCLOUD quota API
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.quota.model;


/**
 * userQuotaResVo
 */
public class UserQuotaResVo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 用户pin
     */
    private String pin;

    /**
     * 业务线
     */
    private String appCode;

    /**
     * 产品线
     */
    private String serviceCode;

    /**
     * 产品线名称
     */
    private String serviceName;

    /**
     * 地域
     */
    private String region;

    /**
     * 地域名称
     */
    private String regionName;

    /**
     * 用户该地域该资源下的配额值
     */
    private Integer userQuota;

    /**
     * 用户该地域该资源下的最大可用配额值
     */
    private Integer maxUserQuota;

    /**
     * 配额到期时间
     */
    private String expireTime;

    /**
     * 可用配额
     */
    private Integer availableQuota;

    /**
     * 预占配额
     */
    private Integer preOccupyAmount;

    /**
     * 创建时间
     */
    private String createdTime;

    /**
     * 更新时间
     */
    private String updatedTime;

    /**
     * 资源id
     */
    private String resourceId;

    /**
     * 父资源id
     */
    private String parentResourceId;

    /**
     * 产品名称
     */
    private String productName;

    /**
     * 站点类型
     */
    private Integer siteType;

    /**
     * 已用配额
     */
    private Integer quotaAmount;

    /**
     * 配额超出标识,[已使用配额，大于等于配额总量，false]，[已使用配额，小于配额总量，返回true]
     */
    private Boolean quotaBeyondFlag;

    /**
     * 是否资资源
     */
    private String isSubResource;

    /**
     * 失败原因
     */
    private String failReason;


    /**
     * get 用户pin
     *
     * @return
     */
    public String getPin() {
        return pin;
    }

    /**
     * set 用户pin
     *
     * @param pin
     */
    public void setPin(String pin) {
        this.pin = pin;
    }

    /**
     * get 业务线
     *
     * @return
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * set 业务线
     *
     * @param appCode
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * get 产品线
     *
     * @return
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * set 产品线
     *
     * @param serviceCode
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    /**
     * get 产品线名称
     *
     * @return
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * set 产品线名称
     *
     * @param serviceName
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * get 地域
     *
     * @return
     */
    public String getRegion() {
        return region;
    }

    /**
     * set 地域
     *
     * @param region
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * get 地域名称
     *
     * @return
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * set 地域名称
     *
     * @param regionName
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * get 用户该地域该资源下的配额值
     *
     * @return
     */
    public Integer getUserQuota() {
        return userQuota;
    }

    /**
     * set 用户该地域该资源下的配额值
     *
     * @param userQuota
     */
    public void setUserQuota(Integer userQuota) {
        this.userQuota = userQuota;
    }

    /**
     * get 用户该地域该资源下的最大可用配额值
     *
     * @return
     */
    public Integer getMaxUserQuota() {
        return maxUserQuota;
    }

    /**
     * set 用户该地域该资源下的最大可用配额值
     *
     * @param maxUserQuota
     */
    public void setMaxUserQuota(Integer maxUserQuota) {
        this.maxUserQuota = maxUserQuota;
    }

    /**
     * get 配额到期时间
     *
     * @return
     */
    public String getExpireTime() {
        return expireTime;
    }

    /**
     * set 配额到期时间
     *
     * @param expireTime
     */
    public void setExpireTime(String expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * get 可用配额
     *
     * @return
     */
    public Integer getAvailableQuota() {
        return availableQuota;
    }

    /**
     * set 可用配额
     *
     * @param availableQuota
     */
    public void setAvailableQuota(Integer availableQuota) {
        this.availableQuota = availableQuota;
    }

    /**
     * get 预占配额
     *
     * @return
     */
    public Integer getPreOccupyAmount() {
        return preOccupyAmount;
    }

    /**
     * set 预占配额
     *
     * @param preOccupyAmount
     */
    public void setPreOccupyAmount(Integer preOccupyAmount) {
        this.preOccupyAmount = preOccupyAmount;
    }

    /**
     * get 创建时间
     *
     * @return
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * set 创建时间
     *
     * @param createdTime
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * get 更新时间
     *
     * @return
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * set 更新时间
     *
     * @param updatedTime
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * get 资源id
     *
     * @return
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * set 资源id
     *
     * @param resourceId
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * get 父资源id
     *
     * @return
     */
    public String getParentResourceId() {
        return parentResourceId;
    }

    /**
     * set 父资源id
     *
     * @param parentResourceId
     */
    public void setParentResourceId(String parentResourceId) {
        this.parentResourceId = parentResourceId;
    }

    /**
     * get 产品名称
     *
     * @return
     */
    public String getProductName() {
        return productName;
    }

    /**
     * set 产品名称
     *
     * @param productName
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * get 站点类型
     *
     * @return
     */
    public Integer getSiteType() {
        return siteType;
    }

    /**
     * set 站点类型
     *
     * @param siteType
     */
    public void setSiteType(Integer siteType) {
        this.siteType = siteType;
    }

    /**
     * get 已用配额
     *
     * @return
     */
    public Integer getQuotaAmount() {
        return quotaAmount;
    }

    /**
     * set 已用配额
     *
     * @param quotaAmount
     */
    public void setQuotaAmount(Integer quotaAmount) {
        this.quotaAmount = quotaAmount;
    }

    /**
     * get 配额超出标识,[已使用配额，大于等于配额总量，false]，[已使用配额，小于配额总量，返回true]
     *
     * @return
     */
    public Boolean getQuotaBeyondFlag() {
        return quotaBeyondFlag;
    }

    /**
     * set 配额超出标识,[已使用配额，大于等于配额总量，false]，[已使用配额，小于配额总量，返回true]
     *
     * @param quotaBeyondFlag
     */
    public void setQuotaBeyondFlag(Boolean quotaBeyondFlag) {
        this.quotaBeyondFlag = quotaBeyondFlag;
    }

    /**
     * get 是否资资源
     *
     * @return
     */
    public String getIsSubResource() {
        return isSubResource;
    }

    /**
     * set 是否资资源
     *
     * @param isSubResource
     */
    public void setIsSubResource(String isSubResource) {
        this.isSubResource = isSubResource;
    }

    /**
     * get 失败原因
     *
     * @return
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * set 失败原因
     *
     * @param failReason
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }


    /**
     * set 用户pin
     *
     * @param pin
     */
    public UserQuotaResVo pin(String pin) {
        this.pin = pin;
        return this;
    }

    /**
     * set 业务线
     *
     * @param appCode
     */
    public UserQuotaResVo appCode(String appCode) {
        this.appCode = appCode;
        return this;
    }

    /**
     * set 产品线
     *
     * @param serviceCode
     */
    public UserQuotaResVo serviceCode(String serviceCode) {
        this.serviceCode = serviceCode;
        return this;
    }

    /**
     * set 产品线名称
     *
     * @param serviceName
     */
    public UserQuotaResVo serviceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }

    /**
     * set 地域
     *
     * @param region
     */
    public UserQuotaResVo region(String region) {
        this.region = region;
        return this;
    }

    /**
     * set 地域名称
     *
     * @param regionName
     */
    public UserQuotaResVo regionName(String regionName) {
        this.regionName = regionName;
        return this;
    }

    /**
     * set 用户该地域该资源下的配额值
     *
     * @param userQuota
     */
    public UserQuotaResVo userQuota(Integer userQuota) {
        this.userQuota = userQuota;
        return this;
    }

    /**
     * set 用户该地域该资源下的最大可用配额值
     *
     * @param maxUserQuota
     */
    public UserQuotaResVo maxUserQuota(Integer maxUserQuota) {
        this.maxUserQuota = maxUserQuota;
        return this;
    }

    /**
     * set 配额到期时间
     *
     * @param expireTime
     */
    public UserQuotaResVo expireTime(String expireTime) {
        this.expireTime = expireTime;
        return this;
    }

    /**
     * set 可用配额
     *
     * @param availableQuota
     */
    public UserQuotaResVo availableQuota(Integer availableQuota) {
        this.availableQuota = availableQuota;
        return this;
    }

    /**
     * set 预占配额
     *
     * @param preOccupyAmount
     */
    public UserQuotaResVo preOccupyAmount(Integer preOccupyAmount) {
        this.preOccupyAmount = preOccupyAmount;
        return this;
    }

    /**
     * set 创建时间
     *
     * @param createdTime
     */
    public UserQuotaResVo createdTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * set 更新时间
     *
     * @param updatedTime
     */
    public UserQuotaResVo updatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    /**
     * set 资源id
     *
     * @param resourceId
     */
    public UserQuotaResVo resourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * set 父资源id
     *
     * @param parentResourceId
     */
    public UserQuotaResVo parentResourceId(String parentResourceId) {
        this.parentResourceId = parentResourceId;
        return this;
    }

    /**
     * set 产品名称
     *
     * @param productName
     */
    public UserQuotaResVo productName(String productName) {
        this.productName = productName;
        return this;
    }

    /**
     * set 站点类型
     *
     * @param siteType
     */
    public UserQuotaResVo siteType(Integer siteType) {
        this.siteType = siteType;
        return this;
    }

    /**
     * set 已用配额
     *
     * @param quotaAmount
     */
    public UserQuotaResVo quotaAmount(Integer quotaAmount) {
        this.quotaAmount = quotaAmount;
        return this;
    }

    /**
     * set 配额超出标识,[已使用配额，大于等于配额总量，false]，[已使用配额，小于配额总量，返回true]
     *
     * @param quotaBeyondFlag
     */
    public UserQuotaResVo quotaBeyondFlag(Boolean quotaBeyondFlag) {
        this.quotaBeyondFlag = quotaBeyondFlag;
        return this;
    }

    /**
     * set 是否资资源
     *
     * @param isSubResource
     */
    public UserQuotaResVo isSubResource(String isSubResource) {
        this.isSubResource = isSubResource;
        return this;
    }

    /**
     * set 失败原因
     *
     * @param failReason
     */
    public UserQuotaResVo failReason(String failReason) {
        this.failReason = failReason;
        return this;
    }


}