/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.eid.model;


/**
 * deviceRespBody
 */
public class DeviceRespBody  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * tk
     */
    private String tk;

    /**
     * isStrategy
     */
    private String isStrategy;

    /**
     * cltTime
     */
    private Integer cltTime;

    /**
     * cltFreq
     */
    private Integer cltFreq;

    /**
     * isCltSensor
     */
    private String isCltSensor;

    /**
     * tokenTime
     */
    private Number tokenTime;

    /**
     * tokenActTime
     */
    private Number tokenActTime;

    /**
     * eid
     */
    private String eid;

    /**
     * ise
     */
    private String ise;

    /**
     * isr
     */
    private String isr;

    /**
     * ism
     */
    private String ism;

    /**
     * ish
     */
    private String ish;

    /**
     * isj
     */
    private String isj;



    /**
     * get tk
     *
     * @return
     */
    public String getTk() {
        return tk;
    }

    /**
     * set tk
     *
     * @param tk
     */
    public void setTk(String tk) {
        this.tk = tk;
    }


    /**
     * get isStrategy
     *
     * @return
     */
    public String getIsStrategy() {
        return isStrategy;
    }

    /**
     * set isStrategy
     *
     * @param isStrategy
     */
    public void setIsStrategy(String isStrategy) {
        this.isStrategy = isStrategy;
    }


    /**
     * get cltTime
     *
     * @return
     */
    public Integer getCltTime() {
        return cltTime;
    }

    /**
     * set cltTime
     *
     * @param cltTime
     */
    public void setCltTime(Integer cltTime) {
        this.cltTime = cltTime;
    }


    /**
     * get cltFreq
     *
     * @return
     */
    public Integer getCltFreq() {
        return cltFreq;
    }

    /**
     * set cltFreq
     *
     * @param cltFreq
     */
    public void setCltFreq(Integer cltFreq) {
        this.cltFreq = cltFreq;
    }


    /**
     * get isCltSensor
     *
     * @return
     */
    public String getIsCltSensor() {
        return isCltSensor;
    }

    /**
     * set isCltSensor
     *
     * @param isCltSensor
     */
    public void setIsCltSensor(String isCltSensor) {
        this.isCltSensor = isCltSensor;
    }


    /**
     * get tokenTime
     *
     * @return
     */
    public Number getTokenTime() {
        return tokenTime;
    }

    /**
     * set tokenTime
     *
     * @param tokenTime
     */
    public void setTokenTime(Number tokenTime) {
        this.tokenTime = tokenTime;
    }


    /**
     * get tokenActTime
     *
     * @return
     */
    public Number getTokenActTime() {
        return tokenActTime;
    }

    /**
     * set tokenActTime
     *
     * @param tokenActTime
     */
    public void setTokenActTime(Number tokenActTime) {
        this.tokenActTime = tokenActTime;
    }


    /**
     * get eid
     *
     * @return
     */
    public String getEid() {
        return eid;
    }

    /**
     * set eid
     *
     * @param eid
     */
    public void setEid(String eid) {
        this.eid = eid;
    }


    /**
     * get ise
     *
     * @return
     */
    public String getIse() {
        return ise;
    }

    /**
     * set ise
     *
     * @param ise
     */
    public void setIse(String ise) {
        this.ise = ise;
    }


    /**
     * get isr
     *
     * @return
     */
    public String getIsr() {
        return isr;
    }

    /**
     * set isr
     *
     * @param isr
     */
    public void setIsr(String isr) {
        this.isr = isr;
    }


    /**
     * get ism
     *
     * @return
     */
    public String getIsm() {
        return ism;
    }

    /**
     * set ism
     *
     * @param ism
     */
    public void setIsm(String ism) {
        this.ism = ism;
    }


    /**
     * get ish
     *
     * @return
     */
    public String getIsh() {
        return ish;
    }

    /**
     * set ish
     *
     * @param ish
     */
    public void setIsh(String ish) {
        this.ish = ish;
    }


    /**
     * get isj
     *
     * @return
     */
    public String getIsj() {
        return isj;
    }

    /**
     * set isj
     *
     * @param isj
     */
    public void setIsj(String isj) {
        this.isj = isj;
    }



    /**
     * set tk
     *
     * @param tk
     */
    public DeviceRespBody tk(String tk) {
        this.tk = tk;
        return this;
    }


    /**
     * set isStrategy
     *
     * @param isStrategy
     */
    public DeviceRespBody isStrategy(String isStrategy) {
        this.isStrategy = isStrategy;
        return this;
    }


    /**
     * set cltTime
     *
     * @param cltTime
     */
    public DeviceRespBody cltTime(Integer cltTime) {
        this.cltTime = cltTime;
        return this;
    }


    /**
     * set cltFreq
     *
     * @param cltFreq
     */
    public DeviceRespBody cltFreq(Integer cltFreq) {
        this.cltFreq = cltFreq;
        return this;
    }


    /**
     * set isCltSensor
     *
     * @param isCltSensor
     */
    public DeviceRespBody isCltSensor(String isCltSensor) {
        this.isCltSensor = isCltSensor;
        return this;
    }


    /**
     * set tokenTime
     *
     * @param tokenTime
     */
    public DeviceRespBody tokenTime(Number tokenTime) {
        this.tokenTime = tokenTime;
        return this;
    }


    /**
     * set tokenActTime
     *
     * @param tokenActTime
     */
    public DeviceRespBody tokenActTime(Number tokenActTime) {
        this.tokenActTime = tokenActTime;
        return this;
    }


    /**
     * set eid
     *
     * @param eid
     */
    public DeviceRespBody eid(String eid) {
        this.eid = eid;
        return this;
    }


    /**
     * set ise
     *
     * @param ise
     */
    public DeviceRespBody ise(String ise) {
        this.ise = ise;
        return this;
    }


    /**
     * set isr
     *
     * @param isr
     */
    public DeviceRespBody isr(String isr) {
        this.isr = isr;
        return this;
    }


    /**
     * set ism
     *
     * @param ism
     */
    public DeviceRespBody ism(String ism) {
        this.ism = ism;
        return this;
    }


    /**
     * set ish
     *
     * @param ish
     */
    public DeviceRespBody ish(String ish) {
        this.ish = ish;
        return this;
    }


    /**
     * set isj
     *
     * @param isj
     */
    public DeviceRespBody isj(String isj) {
        this.isj = isj;
        return this;
    }


}