/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.es.model;


/**
 * azConf
 */
public class AzConf  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * azId
     */
    private String azId;

    /**
     * 数据节点
     */
    private NodeConf dataNode;

    /**
     * 专有主节点
     */
    private NodeConf masterNode;

    /**
     * 协调节点
     */
    private NodeConf coordinatingNode;


    /**
     * get azId
     *
     * @return
     */
    public String getAzId() {
        return azId;
    }

    /**
     * set azId
     *
     * @param azId
     */
    public void setAzId(String azId) {
        this.azId = azId;
    }

    /**
     * get 数据节点
     *
     * @return
     */
    public NodeConf getDataNode() {
        return dataNode;
    }

    /**
     * set 数据节点
     *
     * @param dataNode
     */
    public void setDataNode(NodeConf dataNode) {
        this.dataNode = dataNode;
    }

    /**
     * get 专有主节点
     *
     * @return
     */
    public NodeConf getMasterNode() {
        return masterNode;
    }

    /**
     * set 专有主节点
     *
     * @param masterNode
     */
    public void setMasterNode(NodeConf masterNode) {
        this.masterNode = masterNode;
    }

    /**
     * get 协调节点
     *
     * @return
     */
    public NodeConf getCoordinatingNode() {
        return coordinatingNode;
    }

    /**
     * set 协调节点
     *
     * @param coordinatingNode
     */
    public void setCoordinatingNode(NodeConf coordinatingNode) {
        this.coordinatingNode = coordinatingNode;
    }


    /**
     * set azId
     *
     * @param azId
     */
    public AzConf azId(String azId) {
        this.azId = azId;
        return this;
    }

    /**
     * set 数据节点
     *
     * @param dataNode
     */
    public AzConf dataNode(NodeConf dataNode) {
        this.dataNode = dataNode;
        return this;
    }

    /**
     * set 专有主节点
     *
     * @param masterNode
     */
    public AzConf masterNode(NodeConf masterNode) {
        this.masterNode = masterNode;
        return this;
    }

    /**
     * set 协调节点
     *
     * @param coordinatingNode
     */
    public AzConf coordinatingNode(NodeConf coordinatingNode) {
        this.coordinatingNode = coordinatingNode;
        return this;
    }


}