/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jmr.model;


/**
 * clusterNode
 */
public class ClusterNode  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 节点ID
     */
    private String serverId;

    /**
     * 节点实例信息
     */
    private String instanceInfo;

    /**
     * 节点主机名称
     */
    private String nodeName;

    /**
     * 节点系统盘类型
     */
    private String nodeSystemDiskType;

    /**
     * 节点实例类型
     */
    private String instanceType;

    /**
     * 节点运行状态
     */
    private String nodeStatus;

    /**
     * 节点数据盘类型
     */
    private String nodeDiskType;

    /**
     * 节点类型，MASTER或者SLAVE
     */
    private String nodeType;

    /**
     * 节点外网IP
     */
    private String outerIp;

    /**
     * 节点内网IP
     */
    private String innerIp;

    /**
     * 节点系统盘大小(GB)
     */
    private String nodeSystemDiskVolume;

    /**
     * 节点数据盘大小(GB)
     */
    private String nodeDiskVolume;


    /**
     * get 节点ID
     *
     * @return
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * set 节点ID
     *
     * @param serverId
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * get 节点实例信息
     *
     * @return
     */
    public String getInstanceInfo() {
        return instanceInfo;
    }

    /**
     * set 节点实例信息
     *
     * @param instanceInfo
     */
    public void setInstanceInfo(String instanceInfo) {
        this.instanceInfo = instanceInfo;
    }

    /**
     * get 节点主机名称
     *
     * @return
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * set 节点主机名称
     *
     * @param nodeName
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * get 节点系统盘类型
     *
     * @return
     */
    public String getNodeSystemDiskType() {
        return nodeSystemDiskType;
    }

    /**
     * set 节点系统盘类型
     *
     * @param nodeSystemDiskType
     */
    public void setNodeSystemDiskType(String nodeSystemDiskType) {
        this.nodeSystemDiskType = nodeSystemDiskType;
    }

    /**
     * get 节点实例类型
     *
     * @return
     */
    public String getInstanceType() {
        return instanceType;
    }

    /**
     * set 节点实例类型
     *
     * @param instanceType
     */
    public void setInstanceType(String instanceType) {
        this.instanceType = instanceType;
    }

    /**
     * get 节点运行状态
     *
     * @return
     */
    public String getNodeStatus() {
        return nodeStatus;
    }

    /**
     * set 节点运行状态
     *
     * @param nodeStatus
     */
    public void setNodeStatus(String nodeStatus) {
        this.nodeStatus = nodeStatus;
    }

    /**
     * get 节点数据盘类型
     *
     * @return
     */
    public String getNodeDiskType() {
        return nodeDiskType;
    }

    /**
     * set 节点数据盘类型
     *
     * @param nodeDiskType
     */
    public void setNodeDiskType(String nodeDiskType) {
        this.nodeDiskType = nodeDiskType;
    }

    /**
     * get 节点类型，MASTER或者SLAVE
     *
     * @return
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * set 节点类型，MASTER或者SLAVE
     *
     * @param nodeType
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * get 节点外网IP
     *
     * @return
     */
    public String getOuterIp() {
        return outerIp;
    }

    /**
     * set 节点外网IP
     *
     * @param outerIp
     */
    public void setOuterIp(String outerIp) {
        this.outerIp = outerIp;
    }

    /**
     * get 节点内网IP
     *
     * @return
     */
    public String getInnerIp() {
        return innerIp;
    }

    /**
     * set 节点内网IP
     *
     * @param innerIp
     */
    public void setInnerIp(String innerIp) {
        this.innerIp = innerIp;
    }

    /**
     * get 节点系统盘大小(GB)
     *
     * @return
     */
    public String getNodeSystemDiskVolume() {
        return nodeSystemDiskVolume;
    }

    /**
     * set 节点系统盘大小(GB)
     *
     * @param nodeSystemDiskVolume
     */
    public void setNodeSystemDiskVolume(String nodeSystemDiskVolume) {
        this.nodeSystemDiskVolume = nodeSystemDiskVolume;
    }

    /**
     * get 节点数据盘大小(GB)
     *
     * @return
     */
    public String getNodeDiskVolume() {
        return nodeDiskVolume;
    }

    /**
     * set 节点数据盘大小(GB)
     *
     * @param nodeDiskVolume
     */
    public void setNodeDiskVolume(String nodeDiskVolume) {
        this.nodeDiskVolume = nodeDiskVolume;
    }


    /**
     * set 节点ID
     *
     * @param serverId
     */
    public ClusterNode serverId(String serverId) {
        this.serverId = serverId;
        return this;
    }

    /**
     * set 节点实例信息
     *
     * @param instanceInfo
     */
    public ClusterNode instanceInfo(String instanceInfo) {
        this.instanceInfo = instanceInfo;
        return this;
    }

    /**
     * set 节点主机名称
     *
     * @param nodeName
     */
    public ClusterNode nodeName(String nodeName) {
        this.nodeName = nodeName;
        return this;
    }

    /**
     * set 节点系统盘类型
     *
     * @param nodeSystemDiskType
     */
    public ClusterNode nodeSystemDiskType(String nodeSystemDiskType) {
        this.nodeSystemDiskType = nodeSystemDiskType;
        return this;
    }

    /**
     * set 节点实例类型
     *
     * @param instanceType
     */
    public ClusterNode instanceType(String instanceType) {
        this.instanceType = instanceType;
        return this;
    }

    /**
     * set 节点运行状态
     *
     * @param nodeStatus
     */
    public ClusterNode nodeStatus(String nodeStatus) {
        this.nodeStatus = nodeStatus;
        return this;
    }

    /**
     * set 节点数据盘类型
     *
     * @param nodeDiskType
     */
    public ClusterNode nodeDiskType(String nodeDiskType) {
        this.nodeDiskType = nodeDiskType;
        return this;
    }

    /**
     * set 节点类型，MASTER或者SLAVE
     *
     * @param nodeType
     */
    public ClusterNode nodeType(String nodeType) {
        this.nodeType = nodeType;
        return this;
    }

    /**
     * set 节点外网IP
     *
     * @param outerIp
     */
    public ClusterNode outerIp(String outerIp) {
        this.outerIp = outerIp;
        return this;
    }

    /**
     * set 节点内网IP
     *
     * @param innerIp
     */
    public ClusterNode innerIp(String innerIp) {
        this.innerIp = innerIp;
        return this;
    }

    /**
     * set 节点系统盘大小(GB)
     *
     * @param nodeSystemDiskVolume
     */
    public ClusterNode nodeSystemDiskVolume(String nodeSystemDiskVolume) {
        this.nodeSystemDiskVolume = nodeSystemDiskVolume;
        return this;
    }

    /**
     * set 节点数据盘大小(GB)
     *
     * @param nodeDiskVolume
     */
    public ClusterNode nodeDiskVolume(String nodeDiskVolume) {
        this.nodeDiskVolume = nodeDiskVolume;
        return this;
    }


}