/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * AVSummary-ASR
 * 自动语音识别任务管理接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.mps.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 保存ASR任务模板
 */
public class SaveAsrTaskTemplateRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 提示词
     * Required:true
     */
    @Required
    private String prompt;

    /**
     * 任务唯一标识
     * Required:true
     */
    @Required
    private String taskId;



    /**
     * get 提示词
     *
     * @return
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * set 提示词
     *
     * @param prompt
     */
    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }


    /**
     * get 任务唯一标识
     *
     * @return
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * set 任务唯一标识
     *
     * @param taskId
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }



    /**
     * set 提示词
     *
     * @param prompt 提示词
     * @return SaveAsrTaskTemplateRequest
     */
    public SaveAsrTaskTemplateRequest prompt(String prompt) {
        this.prompt = prompt;
        return this;
    }


    /**
     * set 任务唯一标识
     *
     * @param taskId 任务唯一标识
     * @return SaveAsrTaskTemplateRequest
     */
    public SaveAsrTaskTemplateRequest taskId(String taskId) {
        this.taskId = taskId;
        return this;
    }


}