/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Permission Management
 * Permission Management API
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.iam.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 查询策略列表
 */
public class DescribePermissionsRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 页码
     * Required:true
     */
    @Required
    private Integer pageNumber;

    /**
     * 每页显示数目
     * Required:true
     */
    @Required
    private Integer pageSize;

    /**
     * 关键字
     */
    private String keyword;

    /**
     * 权限类型,0-全部，1-系统权限，2-自定义权限
     * Required:true
     */
    @Required
    private Integer queryType;

    /**
     * Region ID
     * Required:true
     */
    @Required
    private String regionId;



    /**
     * get 页码
     *
     * @return
     */
    public Integer getPageNumber() {
        return pageNumber;
    }

    /**
     * set 页码
     *
     * @param pageNumber
     */
    public void setPageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
    }


    /**
     * get 每页显示数目
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set 每页显示数目
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }


    /**
     * get 关键字
     *
     * @return
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * set 关键字
     *
     * @param keyword
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }


    /**
     * get 权限类型,0-全部，1-系统权限，2-自定义权限
     *
     * @return
     */
    public Integer getQueryType() {
        return queryType;
    }

    /**
     * set 权限类型,0-全部，1-系统权限，2-自定义权限
     *
     * @param queryType
     */
    public void setQueryType(Integer queryType) {
        this.queryType = queryType;
    }


    /**
     * get Region ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set Region ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }



    /**
     * set 页码
     *
     * @param pageNumber
     */
    public DescribePermissionsRequest pageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
        return this;
    }


    /**
     * set 每页显示数目
     *
     * @param pageSize
     */
    public DescribePermissionsRequest pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }


    /**
     * set 关键字
     *
     * @param keyword
     */
    public DescribePermissionsRequest keyword(String keyword) {
        this.keyword = keyword;
        return this;
    }


    /**
     * set 权限类型,0-全部，1-系统权限，2-自定义权限
     *
     * @param queryType
     */
    public DescribePermissionsRequest queryType(Integer queryType) {
        this.queryType = queryType;
        return this;
    }


    /**
     * set Region ID
     *
     * @param regionId
     */
    public DescribePermissionsRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


}