/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.user.model;

import java.util.List;
import java.util.ArrayList;

/**
 * modifyIpSetUpVo
 */
public class ModifyIpSetUpVo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 标题
     */
    private String title;

    /**
     * 标题编码 用户ip白名单为空
     */
    private String titleCode;

    /**
     * 配置方式-0ip白名单，1固定ip白名单
     */
    private Integer type;

    /**
     * pin集合 固定ip白名单入参
     */
    
    private List<String> pins;
    /**
     * pin集合 ip白名单入参
     */
    private String pin;

    /**
     * ip集合
     */
    
    private List<String> ip;
    /**
     * 是否控制网关sdk：0否，1是
     */
    private Integer isApi;



    /**
     * get 标题
     *
     * @return
     */
    public String getTitle() {
        return title;
    }

    /**
     * set 标题
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }


    /**
     * get 标题编码 用户ip白名单为空
     *
     * @return
     */
    public String getTitleCode() {
        return titleCode;
    }

    /**
     * set 标题编码 用户ip白名单为空
     *
     * @param titleCode
     */
    public void setTitleCode(String titleCode) {
        this.titleCode = titleCode;
    }


    /**
     * get 配置方式-0ip白名单，1固定ip白名单
     *
     * @return
     */
    public Integer getType() {
        return type;
    }

    /**
     * set 配置方式-0ip白名单，1固定ip白名单
     *
     * @param type
     */
    public void setType(Integer type) {
        this.type = type;
    }


    /**
    * get pin集合 固定ip白名单入参
    *
    * @return
    */
    public List<String> getPins() {
        return pins;
    }

    /**
    * set pin集合 固定ip白名单入参
    *
    * @param pins
    */
    public void setPins(List<String> pins) {
        this.pins = pins;
    }


    /**
     * get pin集合 ip白名单入参
     *
     * @return
     */
    public String getPin() {
        return pin;
    }

    /**
     * set pin集合 ip白名单入参
     *
     * @param pin
     */
    public void setPin(String pin) {
        this.pin = pin;
    }


    /**
    * get ip集合
    *
    * @return
    */
    public List<String> getIp() {
        return ip;
    }

    /**
    * set ip集合
    *
    * @param ip
    */
    public void setIp(List<String> ip) {
        this.ip = ip;
    }


    /**
     * get 是否控制网关sdk：0否，1是
     *
     * @return
     */
    public Integer getIsApi() {
        return isApi;
    }

    /**
     * set 是否控制网关sdk：0否，1是
     *
     * @param isApi
     */
    public void setIsApi(Integer isApi) {
        this.isApi = isApi;
    }



    /**
     * set 标题
     *
     * @param title
     */
    public ModifyIpSetUpVo title(String title) {
        this.title = title;
        return this;
    }


    /**
     * set 标题编码 用户ip白名单为空
     *
     * @param titleCode
     */
    public ModifyIpSetUpVo titleCode(String titleCode) {
        this.titleCode = titleCode;
        return this;
    }


    /**
     * set 配置方式-0ip白名单，1固定ip白名单
     *
     * @param type
     */
    public ModifyIpSetUpVo type(Integer type) {
        this.type = type;
        return this;
    }


    /**
    * set pin集合 固定ip白名单入参
    *
    * @param pins
    */
    public ModifyIpSetUpVo pins(List<String> pins) {
        this.pins = pins;
        return this;
    }


    /**
     * set pin集合 ip白名单入参
     *
     * @param pin
     */
    public ModifyIpSetUpVo pin(String pin) {
        this.pin = pin;
        return this;
    }


    /**
    * set ip集合
    *
    * @param ip
    */
    public ModifyIpSetUpVo ip(List<String> ip) {
        this.ip = ip;
        return this;
    }


    /**
     * set 是否控制网关sdk：0否，1是
     *
     * @param isApi
     */
    public ModifyIpSetUpVo isApi(Integer isApi) {
        this.isApi = isApi;
        return this;
    }



    /**
     * add item to pin集合 固定ip白名单入参
     *
     * @param pin
     */
    public void addPin(String pin) {
        if (this.pins == null) {
            this.pins = new ArrayList<>();
        }
        this.pins.add(pin);
    }

    /**
     * add item to ip集合
     *
     * @param ip
     */
    public void addIp(String ip) {
        if (this.ip == null) {
            this.ip = new ArrayList<>();
        }
        this.ip.add(ip);
    }
}