/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.smartdba.model;


/**
 * metricResourceModel
 */
public class MetricResourceModel  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 实例id
     */
    private String instanceId;

    /**
     * 实例名称
     */
    private String instanceName;

    /**
     * 数据库版本, 如:MySQL 5.7
     */
    private String engineVersion;

    /**
     * 实例规格
     */
    private String instanceClass;

    /**
     * 值
     */
    private String value;


    /**
     * get 实例id
     *
     * @return
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * set 实例id
     *
     * @param instanceId
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * get 实例名称
     *
     * @return
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * set 实例名称
     *
     * @param instanceName
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    /**
     * get 数据库版本, 如:MySQL 5.7
     *
     * @return
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * set 数据库版本, 如:MySQL 5.7
     *
     * @param engineVersion
     */
    public void setEngineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
    }

    /**
     * get 实例规格
     *
     * @return
     */
    public String getInstanceClass() {
        return instanceClass;
    }

    /**
     * set 实例规格
     *
     * @param instanceClass
     */
    public void setInstanceClass(String instanceClass) {
        this.instanceClass = instanceClass;
    }

    /**
     * get 值
     *
     * @return
     */
    public String getValue() {
        return value;
    }

    /**
     * set 值
     *
     * @param value
     */
    public void setValue(String value) {
        this.value = value;
    }


    /**
     * set 实例id
     *
     * @param instanceId
     */
    public MetricResourceModel instanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }

    /**
     * set 实例名称
     *
     * @param instanceName
     */
    public MetricResourceModel instanceName(String instanceName) {
        this.instanceName = instanceName;
        return this;
    }

    /**
     * set 数据库版本, 如:MySQL 5.7
     *
     * @param engineVersion
     */
    public MetricResourceModel engineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
        return this;
    }

    /**
     * set 实例规格
     *
     * @param instanceClass
     */
    public MetricResourceModel instanceClass(String instanceClass) {
        this.instanceClass = instanceClass;
        return this;
    }

    /**
     * set 值
     *
     * @param value
     */
    public MetricResourceModel value(String value) {
        this.value = value;
        return this;
    }


}