/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.smartdba.model;


/**
 * metric
 */
public class Metric  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 单位
     */
    private String calculateUnit;

    /**
     * metric名称
     */
    private String metric;

    /**
     * metric中文名称
     */
    private String metricName;

    /**
     * metric功能描述
     */
    private String metricDescribe;


    /**
     * get 单位
     *
     * @return
     */
    public String getCalculateUnit() {
        return calculateUnit;
    }

    /**
     * set 单位
     *
     * @param calculateUnit
     */
    public void setCalculateUnit(String calculateUnit) {
        this.calculateUnit = calculateUnit;
    }

    /**
     * get metric名称
     *
     * @return
     */
    public String getMetric() {
        return metric;
    }

    /**
     * set metric名称
     *
     * @param metric
     */
    public void setMetric(String metric) {
        this.metric = metric;
    }

    /**
     * get metric中文名称
     *
     * @return
     */
    public String getMetricName() {
        return metricName;
    }

    /**
     * set metric中文名称
     *
     * @param metricName
     */
    public void setMetricName(String metricName) {
        this.metricName = metricName;
    }

    /**
     * get metric功能描述
     *
     * @return
     */
    public String getMetricDescribe() {
        return metricDescribe;
    }

    /**
     * set metric功能描述
     *
     * @param metricDescribe
     */
    public void setMetricDescribe(String metricDescribe) {
        this.metricDescribe = metricDescribe;
    }


    /**
     * set 单位
     *
     * @param calculateUnit
     */
    public Metric calculateUnit(String calculateUnit) {
        this.calculateUnit = calculateUnit;
        return this;
    }

    /**
     * set metric名称
     *
     * @param metric
     */
    public Metric metric(String metric) {
        this.metric = metric;
        return this;
    }

    /**
     * set metric中文名称
     *
     * @param metricName
     */
    public Metric metricName(String metricName) {
        this.metricName = metricName;
        return this;
    }

    /**
     * set metric功能描述
     *
     * @param metricDescribe
     */
    public Metric metricDescribe(String metricDescribe) {
        this.metricDescribe = metricDescribe;
        return this;
    }


}