/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;


/**
 * failedInstanceVo
 */
public class FailedInstanceVo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 作业名
     */
    private String jobName;

    /**
     * 租户编码
     */
    private String companyCode;

    /**
     * 工作空间编码
     */
    private String workspaceCode;

    /**
     * 实例ID
     */
    private String instanceId;

    /**
     * application id
     */
    private String applicationId;

    /**
     * 作业类型
     */
    private String jobType;

    /**
     * 数据日期
     */
    private String txDate;

    /**
     * 创建时间
     */
    private String createTime;



    /**
     * get 作业名
     *
     * @return
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * set 作业名
     *
     * @param jobName
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }


    /**
     * get 租户编码
     *
     * @return
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * set 租户编码
     *
     * @param companyCode
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }


    /**
     * get 工作空间编码
     *
     * @return
     */
    public String getWorkspaceCode() {
        return workspaceCode;
    }

    /**
     * set 工作空间编码
     *
     * @param workspaceCode
     */
    public void setWorkspaceCode(String workspaceCode) {
        this.workspaceCode = workspaceCode;
    }


    /**
     * get 实例ID
     *
     * @return
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * set 实例ID
     *
     * @param instanceId
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }


    /**
     * get application id
     *
     * @return
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * set application id
     *
     * @param applicationId
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }


    /**
     * get 作业类型
     *
     * @return
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * set 作业类型
     *
     * @param jobType
     */
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }


    /**
     * get 数据日期
     *
     * @return
     */
    public String getTxDate() {
        return txDate;
    }

    /**
     * set 数据日期
     *
     * @param txDate
     */
    public void setTxDate(String txDate) {
        this.txDate = txDate;
    }


    /**
     * get 创建时间
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 创建时间
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }



    /**
     * set 作业名
     *
     * @param jobName 作业名
     * @return FailedInstanceVo
     */
    public FailedInstanceVo jobName(String jobName) {
        this.jobName = jobName;
        return this;
    }


    /**
     * set 租户编码
     *
     * @param companyCode 租户编码
     * @return FailedInstanceVo
     */
    public FailedInstanceVo companyCode(String companyCode) {
        this.companyCode = companyCode;
        return this;
    }


    /**
     * set 工作空间编码
     *
     * @param workspaceCode 工作空间编码
     * @return FailedInstanceVo
     */
    public FailedInstanceVo workspaceCode(String workspaceCode) {
        this.workspaceCode = workspaceCode;
        return this;
    }


    /**
     * set 实例ID
     *
     * @param instanceId 实例ID
     * @return FailedInstanceVo
     */
    public FailedInstanceVo instanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }


    /**
     * set application id
     *
     * @param applicationId application id
     * @return FailedInstanceVo
     */
    public FailedInstanceVo applicationId(String applicationId) {
        this.applicationId = applicationId;
        return this;
    }


    /**
     * set 作业类型
     *
     * @param jobType 作业类型
     * @return FailedInstanceVo
     */
    public FailedInstanceVo jobType(String jobType) {
        this.jobType = jobType;
        return this;
    }


    /**
     * set 数据日期
     *
     * @param txDate 数据日期
     * @return FailedInstanceVo
     */
    public FailedInstanceVo txDate(String txDate) {
        this.txDate = txDate;
        return this;
    }


    /**
     * set 创建时间
     *
     * @param createTime 创建时间
     * @return FailedInstanceVo
     */
    public FailedInstanceVo createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }


}