/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ShenHaiPlatform Admin Manage APIs
 * 数据字典管理
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 根据类型获取数据字典
 */
public class GravityParticleSchedDictGetByTypeRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 数据字典id
     */
    private Long id;

    /**
     * 数据字典code
     */
    private String dictCode;

    /**
     * 数据字典父级code
     */
    private String pDictCode;

    /**
     * 数据字典名称
     */
    private String dictName;

    /**
     * 数据字典排序
     */
    private Integer dictSort;

    /**
     * 数据字典备份
     */
    private String dictBak;

    /**
     * 数据字典描述
     */
    private String dictDesc;

    /**
     * 是否有效 1: 有效, 0: 无效
     */
    private String isValid;

    /**
     * 是否删除 1: 删除, 0: 未删除
     */
    private String isDel;

    /**
     * 创建时间
     */
    private String createdTime;

    /**
     * 修改时间
     */
    private String modifiedTime;

    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 应用名称
     * Required:true
     */
    @Required
    private String appName;



    /**
     * get 数据字典id
     *
     * @return
     */
    public Long getId() {
        return id;
    }

    /**
     * set 数据字典id
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * get 数据字典code
     *
     * @return
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * set 数据字典code
     *
     * @param dictCode
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }


    /**
     * get 数据字典父级code
     *
     * @return
     */
    public String getPDictCode() {
        return pDictCode;
    }

    /**
     * set 数据字典父级code
     *
     * @param pDictCode
     */
    public void setPDictCode(String pDictCode) {
        this.pDictCode = pDictCode;
    }


    /**
     * get 数据字典名称
     *
     * @return
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * set 数据字典名称
     *
     * @param dictName
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }


    /**
     * get 数据字典排序
     *
     * @return
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * set 数据字典排序
     *
     * @param dictSort
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }


    /**
     * get 数据字典备份
     *
     * @return
     */
    public String getDictBak() {
        return dictBak;
    }

    /**
     * set 数据字典备份
     *
     * @param dictBak
     */
    public void setDictBak(String dictBak) {
        this.dictBak = dictBak;
    }


    /**
     * get 数据字典描述
     *
     * @return
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * set 数据字典描述
     *
     * @param dictDesc
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc;
    }


    /**
     * get 是否有效 1: 有效, 0: 无效
     *
     * @return
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set 是否有效 1: 有效, 0: 无效
     *
     * @param isValid
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }


    /**
     * get 是否删除 1: 删除, 0: 未删除
     *
     * @return
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * set 是否删除 1: 删除, 0: 未删除
     *
     * @param isDel
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }


    /**
     * get 创建时间
     *
     * @return
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * set 创建时间
     *
     * @param createdTime
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }


    /**
     * get 修改时间
     *
     * @return
     */
    public String getModifiedTime() {
        return modifiedTime;
    }

    /**
     * set 修改时间
     *
     * @param modifiedTime
     */
    public void setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime;
    }


    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 应用名称
     *
     * @return
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set 应用名称
     *
     * @param appName
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }



    /**
     * set 数据字典id
     *
     * @param id
     */
    public GravityParticleSchedDictGetByTypeRequest id(Long id) {
        this.id = id;
        return this;
    }


    /**
     * set 数据字典code
     *
     * @param dictCode
     */
    public GravityParticleSchedDictGetByTypeRequest dictCode(String dictCode) {
        this.dictCode = dictCode;
        return this;
    }


    /**
     * set 数据字典父级code
     *
     * @param pDictCode
     */
    public GravityParticleSchedDictGetByTypeRequest pDictCode(String pDictCode) {
        this.pDictCode = pDictCode;
        return this;
    }


    /**
     * set 数据字典名称
     *
     * @param dictName
     */
    public GravityParticleSchedDictGetByTypeRequest dictName(String dictName) {
        this.dictName = dictName;
        return this;
    }


    /**
     * set 数据字典排序
     *
     * @param dictSort
     */
    public GravityParticleSchedDictGetByTypeRequest dictSort(Integer dictSort) {
        this.dictSort = dictSort;
        return this;
    }


    /**
     * set 数据字典备份
     *
     * @param dictBak
     */
    public GravityParticleSchedDictGetByTypeRequest dictBak(String dictBak) {
        this.dictBak = dictBak;
        return this;
    }


    /**
     * set 数据字典描述
     *
     * @param dictDesc
     */
    public GravityParticleSchedDictGetByTypeRequest dictDesc(String dictDesc) {
        this.dictDesc = dictDesc;
        return this;
    }


    /**
     * set 是否有效 1: 有效, 0: 无效
     *
     * @param isValid
     */
    public GravityParticleSchedDictGetByTypeRequest isValid(String isValid) {
        this.isValid = isValid;
        return this;
    }


    /**
     * set 是否删除 1: 删除, 0: 未删除
     *
     * @param isDel
     */
    public GravityParticleSchedDictGetByTypeRequest isDel(String isDel) {
        this.isDel = isDel;
        return this;
    }


    /**
     * set 创建时间
     *
     * @param createdTime
     */
    public GravityParticleSchedDictGetByTypeRequest createdTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }


    /**
     * set 修改时间
     *
     * @param modifiedTime
     */
    public GravityParticleSchedDictGetByTypeRequest modifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime;
        return this;
    }


    /**
     * set 地域ID
     *
     * @param regionId
     */
    public GravityParticleSchedDictGetByTypeRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 应用名称
     *
     * @param appName
     */
    public GravityParticleSchedDictGetByTypeRequest appName(String appName) {
        this.appName = appName;
        return this;
    }


}