/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Jtlas Warehouse Search API
 * 云仓引擎元数据查询:支持详情，分区，权限等能力
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import com.jdcloud.sdk.service.JdcloudResponse;

/**
 * 根据租户/项目空间/表名称查询表详情
 */
public class JtlasWarehouseTableDetailResponse extends JdcloudResponse<JtlasWarehouseTableDetailResult> implements java.io.Serializable {

    private static final long serialVersionUID = 1L;




}