/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;


/**
 * taskPipeInfoRes
 */
public class TaskPipeInfoRes  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 任务管道基础信息
     */
    private TaskPipeBasicInfoRes basicInfo;

    /**
     * 任务管道数据源信息
     */
    private TaskPipeDatasourceInfoRes datasourceInfo;

    /**
     * 任务管道设置信息
     */
    private TaskPipeSettingInfoRes settingInfo;

    /**
     * 数据集成任务的writer/reader配置信息
     */
    private String executeJson;



    /**
     * get 任务管道基础信息
     *
     * @return
     */
    public TaskPipeBasicInfoRes getBasicInfo() {
        return basicInfo;
    }

    /**
     * set 任务管道基础信息
     *
     * @param basicInfo
     */
    public void setBasicInfo(TaskPipeBasicInfoRes basicInfo) {
        this.basicInfo = basicInfo;
    }


    /**
     * get 任务管道数据源信息
     *
     * @return
     */
    public TaskPipeDatasourceInfoRes getDatasourceInfo() {
        return datasourceInfo;
    }

    /**
     * set 任务管道数据源信息
     *
     * @param datasourceInfo
     */
    public void setDatasourceInfo(TaskPipeDatasourceInfoRes datasourceInfo) {
        this.datasourceInfo = datasourceInfo;
    }


    /**
     * get 任务管道设置信息
     *
     * @return
     */
    public TaskPipeSettingInfoRes getSettingInfo() {
        return settingInfo;
    }

    /**
     * set 任务管道设置信息
     *
     * @param settingInfo
     */
    public void setSettingInfo(TaskPipeSettingInfoRes settingInfo) {
        this.settingInfo = settingInfo;
    }


    /**
     * get 数据集成任务的writer/reader配置信息
     *
     * @return
     */
    public String getExecuteJson() {
        return executeJson;
    }

    /**
     * set 数据集成任务的writer/reader配置信息
     *
     * @param executeJson
     */
    public void setExecuteJson(String executeJson) {
        this.executeJson = executeJson;
    }



    /**
     * set 任务管道基础信息
     *
     * @param basicInfo 任务管道基础信息
     * @return TaskPipeInfoRes
     */
    public TaskPipeInfoRes basicInfo(TaskPipeBasicInfoRes basicInfo) {
        this.basicInfo = basicInfo;
        return this;
    }


    /**
     * set 任务管道数据源信息
     *
     * @param datasourceInfo 任务管道数据源信息
     * @return TaskPipeInfoRes
     */
    public TaskPipeInfoRes datasourceInfo(TaskPipeDatasourceInfoRes datasourceInfo) {
        this.datasourceInfo = datasourceInfo;
        return this;
    }


    /**
     * set 任务管道设置信息
     *
     * @param settingInfo 任务管道设置信息
     * @return TaskPipeInfoRes
     */
    public TaskPipeInfoRes settingInfo(TaskPipeSettingInfoRes settingInfo) {
        this.settingInfo = settingInfo;
        return this;
    }


    /**
     * set 数据集成任务的writer/reader配置信息
     *
     * @param executeJson 数据集成任务的writer/reader配置信息
     * @return TaskPipeInfoRes
     */
    public TaskPipeInfoRes executeJson(String executeJson) {
        this.executeJson = executeJson;
        return this;
    }


}