/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import java.util.List;
import java.util.ArrayList;

/**
 * taskAlarmInfoRes
 */
public class TaskAlarmInfoRes  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 草稿 ID
     */
    private String draftId;

    /**
     * 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
     */
    
    private List<String> method;
    /**
     * 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
     */
    
    private List<String> timing;
    /**
     * 开始延迟时间
     */
    private String startdelayTime;

    /**
     * 完成延迟时间
     */
    private String finishdelayTime;

    /**
     * 接收者列表
     */
    
    private List<String> receiver;


    /**
     * get 草稿 ID
     *
     * @return
     */
    public String getDraftId() {
        return draftId;
    }

    /**
     * set 草稿 ID
     *
     * @param draftId
     */
    public void setDraftId(String draftId) {
        this.draftId = draftId;
    }


    /**
    * get 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
    *
    * @return
    */
    public List<String> getMethod() {
        return method;
    }

    /**
    * set 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
    *
    * @param method
    */
    public void setMethod(List<String> method) {
        this.method = method;
    }


    /**
    * get 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
    *
    * @return
    */
    public List<String> getTiming() {
        return timing;
    }

    /**
    * set 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
    *
    * @param timing
    */
    public void setTiming(List<String> timing) {
        this.timing = timing;
    }


    /**
     * get 开始延迟时间
     *
     * @return
     */
    public String getStartdelayTime() {
        return startdelayTime;
    }

    /**
     * set 开始延迟时间
     *
     * @param startdelayTime
     */
    public void setStartdelayTime(String startdelayTime) {
        this.startdelayTime = startdelayTime;
    }


    /**
     * get 完成延迟时间
     *
     * @return
     */
    public String getFinishdelayTime() {
        return finishdelayTime;
    }

    /**
     * set 完成延迟时间
     *
     * @param finishdelayTime
     */
    public void setFinishdelayTime(String finishdelayTime) {
        this.finishdelayTime = finishdelayTime;
    }


    /**
    * get 接收者列表
    *
    * @return
    */
    public List<String> getReceiver() {
        return receiver;
    }

    /**
    * set 接收者列表
    *
    * @param receiver
    */
    public void setReceiver(List<String> receiver) {
        this.receiver = receiver;
    }



    /**
     * set 草稿 ID
     *
     * @param draftId 草稿 ID
     * @return TaskAlarmInfoRes
     */
    public TaskAlarmInfoRes draftId(String draftId) {
        this.draftId = draftId;
        return this;
    }


    /**
    * set 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
    *
    * @param method 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
    * @return TaskAlarmInfoRes
    */
    public TaskAlarmInfoRes method(List<String> method) {
        this.method = method;
        return this;
    }


    /**
    * set 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
    *
    * @param timing 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
    * @return TaskAlarmInfoRes
    */
    public TaskAlarmInfoRes timing(List<String> timing) {
        this.timing = timing;
        return this;
    }


    /**
     * set 开始延迟时间
     *
     * @param startdelayTime 开始延迟时间
     * @return TaskAlarmInfoRes
     */
    public TaskAlarmInfoRes startdelayTime(String startdelayTime) {
        this.startdelayTime = startdelayTime;
        return this;
    }


    /**
     * set 完成延迟时间
     *
     * @param finishdelayTime 完成延迟时间
     * @return TaskAlarmInfoRes
     */
    public TaskAlarmInfoRes finishdelayTime(String finishdelayTime) {
        this.finishdelayTime = finishdelayTime;
        return this;
    }


    /**
    * set 接收者列表
    *
    * @param receiver 接收者列表
    * @return TaskAlarmInfoRes
    */
    public TaskAlarmInfoRes receiver(List<String> receiver) {
        this.receiver = receiver;
        return this;
    }



    /**
     * add item to 任务告警方式，mail(&quot;邮件&quot;)、website(&quot;站内信&quot;)、phone(&quot;语音&quot;)、message(&quot;短信&quot;)、outWebsite(&quot;机器人&quot;)
     *
     * @param method
     */
    public void addMethod(String method) {
        if (this.method == null) {
            this.method = new ArrayList<>();
        }
        this.method.add(method);
    }

    /**
     * add item to 任务告警时机，finalFailed(&quot;最终失败&quot;)、everyFailed(&quot;每次失败&quot;)、success(&quot;成功完成&quot;)、startDelay(&quot;启动延迟&quot;)、finishDelay(&quot;结束延迟&quot;)
     *
     * @param timing
     */
    public void addTiming(String timing) {
        if (this.timing == null) {
            this.timing = new ArrayList<>();
        }
        this.timing.add(timing);
    }

    /**
     * add item to 接收者列表
     *
     * @param receiver
     */
    public void addReceiver(String receiver) {
        if (this.receiver == null) {
            this.receiver = new ArrayList<>();
        }
        this.receiver.add(receiver);
    }
}