/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ShenHaiPlatform Uranus Task APIs
 * 数据开发-任务业务目录管理相关操作
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 批量预发布节点请求正确的发布顺序
 */
public class UranusFlowPrepublishNodesSortRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 工作流草稿id
     */
    private String flowDraftId;

    /**
     * 该工作流内部任务的草稿id
     */
    
    private List<String> taskDraftIds;
    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 应用名称
     * Required:true
     */
    @Required
    private String appName;



    /**
     * get 工作流草稿id
     *
     * @return
     */
    public String getFlowDraftId() {
        return flowDraftId;
    }

    /**
     * set 工作流草稿id
     *
     * @param flowDraftId
     */
    public void setFlowDraftId(String flowDraftId) {
        this.flowDraftId = flowDraftId;
    }


    /**
    * get 该工作流内部任务的草稿id
    *
    * @return
    */
    public List<String> getTaskDraftIds() {
        return taskDraftIds;
    }

    /**
    * set 该工作流内部任务的草稿id
    *
    * @param taskDraftIds
    */
    public void setTaskDraftIds(List<String> taskDraftIds) {
        this.taskDraftIds = taskDraftIds;
    }


    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 应用名称
     *
     * @return
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set 应用名称
     *
     * @param appName
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }



    /**
     * set 工作流草稿id
     *
     * @param flowDraftId 工作流草稿id
     * @return UranusFlowPrepublishNodesSortRequest
     */
    public UranusFlowPrepublishNodesSortRequest flowDraftId(String flowDraftId) {
        this.flowDraftId = flowDraftId;
        return this;
    }


    /**
    * set 该工作流内部任务的草稿id
    *
    * @param taskDraftIds 该工作流内部任务的草稿id
    * @return UranusFlowPrepublishNodesSortRequest
    */
    public UranusFlowPrepublishNodesSortRequest taskDraftIds(List<String> taskDraftIds) {
        this.taskDraftIds = taskDraftIds;
        return this;
    }


    /**
     * set 地域ID
     *
     * @param regionId 地域ID
     * @return UranusFlowPrepublishNodesSortRequest
     */
    public UranusFlowPrepublishNodesSortRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 应用名称
     *
     * @param appName 应用名称
     * @return UranusFlowPrepublishNodesSortRequest
     */
    public UranusFlowPrepublishNodesSortRequest appName(String appName) {
        this.appName = appName;
        return this;
    }



    /**
     * add item to 该工作流内部任务的草稿id
     *
     * @param taskDraftId
     */
    public void addTaskDraftId(String taskDraftId) {
        if (this.taskDraftIds == null) {
            this.taskDraftIds = new ArrayList<>();
        }
        this.taskDraftIds.add(taskDraftId);
    }
}