/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ShenHaiPlatform Uranus Task APIs
 * 数据开发-任务业务目录管理相关操作
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 任务业务目录是否存在
 */
public class UranusTaskCatalogExistedRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 执行id
     * Required:true
     */
    @Required
    private String catalogName;

    /**
     * 父目录的id，例如 biz_12
     */
    private String parentBizId;

    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 应用名称
     * Required:true
     */
    @Required
    private String appName;



    /**
     * get 执行id
     *
     * @return
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * set 执行id
     *
     * @param catalogName
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }


    /**
     * get 父目录的id，例如 biz_12
     *
     * @return
     */
    public String getParentBizId() {
        return parentBizId;
    }

    /**
     * set 父目录的id，例如 biz_12
     *
     * @param parentBizId
     */
    public void setParentBizId(String parentBizId) {
        this.parentBizId = parentBizId;
    }


    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 应用名称
     *
     * @return
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set 应用名称
     *
     * @param appName
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }



    /**
     * set 执行id
     *
     * @param catalogName 执行id
     * @return UranusTaskCatalogExistedRequest
     */
    public UranusTaskCatalogExistedRequest catalogName(String catalogName) {
        this.catalogName = catalogName;
        return this;
    }


    /**
     * set 父目录的id，例如 biz_12
     *
     * @param parentBizId 父目录的id，例如 biz_12
     * @return UranusTaskCatalogExistedRequest
     */
    public UranusTaskCatalogExistedRequest parentBizId(String parentBizId) {
        this.parentBizId = parentBizId;
        return this;
    }


    /**
     * set 地域ID
     *
     * @param regionId 地域ID
     * @return UranusTaskCatalogExistedRequest
     */
    public UranusTaskCatalogExistedRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 应用名称
     *
     * @param appName 应用名称
     * @return UranusTaskCatalogExistedRequest
     */
    public UranusTaskCatalogExistedRequest appName(String appName) {
        this.appName = appName;
        return this;
    }


}