/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * WorkspaceUserController
 * 工作空间WorkspaceUserController接口
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.shenhaiplatform.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.shenhaiplatform.model.UserRoleInfo;
import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 更改用户角色
 */
public class WorkspaceUpdateUserRoleRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * workspaceId
     */
    private Long workspaceId;

    /**
     * updateRoleReq
     */
    
    private List<UserRoleInfo> updateRoleReq;
    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 应用名称
     * Required:true
     */
    @Required
    private String appName;



    /**
     * get workspaceId
     *
     * @return
     */
    public Long getWorkspaceId() {
        return workspaceId;
    }

    /**
     * set workspaceId
     *
     * @param workspaceId
     */
    public void setWorkspaceId(Long workspaceId) {
        this.workspaceId = workspaceId;
    }


    /**
    * get updateRoleReq
    *
    * @return
    */
    public List<UserRoleInfo> getUpdateRoleReq() {
        return updateRoleReq;
    }

    /**
    * set updateRoleReq
    *
    * @param updateRoleReq
    */
    public void setUpdateRoleReq(List<UserRoleInfo> updateRoleReq) {
        this.updateRoleReq = updateRoleReq;
    }


    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 应用名称
     *
     * @return
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set 应用名称
     *
     * @param appName
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }



    /**
     * set workspaceId
     *
     * @param workspaceId
     */
    public WorkspaceUpdateUserRoleRequest workspaceId(Long workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }


    /**
    * set updateRoleReq
    *
    * @param updateRoleReq
    */
    public WorkspaceUpdateUserRoleRequest updateRoleReq(List<UserRoleInfo> updateRoleReq) {
        this.updateRoleReq = updateRoleReq;
        return this;
    }


    /**
     * set 地域ID
     *
     * @param regionId
     */
    public WorkspaceUpdateUserRoleRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 应用名称
     *
     * @param appName
     */
    public WorkspaceUpdateUserRoleRequest appName(String appName) {
        this.appName = appName;
        return this;
    }



    /**
     * add item to updateRoleReq
     *
     * @param updateRoleReq
     */
    public void addUpdateRoleReq(UserRoleInfo updateRoleReq) {
        if (this.updateRoleReq == null) {
            this.updateRoleReq = new ArrayList<>();
        }
        this.updateRoleReq.add(updateRoleReq);
    }
}