/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 性能统计
 * 性能统计相关接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.rds.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 根据用户定义的查询条件，获取正在执行中的SQL执行的性能信息。用户可以根据这些信息查找与SQL执行相关的性能瓶颈，并进行优化。&lt;br&gt;- 仅支持SQL Server
 */
public class DescribeActiveQueryPerformanceRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 需要查询的数据库名，多个数据库名之间用英文逗号分隔，默认所有数据库
     */
    private String db;

    /**
     * 返回执行时间大于等于threshold的记录，默认10，单位秒
     */
    private Integer threshold;

    /**
     * 显示数据的页码，默认为1，取值范围：[-1,1000)。pageNumber为-1时，返回所有数据页码；超过总页数时，显示最后一页。
     */
    private Integer pageNumber;

    /**
     * 每页显示的数据条数，默认为50，取值范围：[1,100]，只能为10的倍数
     */
    private Integer pageSize;

    /**
     * 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * RDS 实例ID，唯一标识一个RDS实例
     * Required:true
     */
    @Required
    private String instanceId;


    /**
     * get 需要查询的数据库名，多个数据库名之间用英文逗号分隔，默认所有数据库
     *
     * @return
     */
    public String getDb() {
        return db;
    }

    /**
     * set 需要查询的数据库名，多个数据库名之间用英文逗号分隔，默认所有数据库
     *
     * @param db
     */
    public void setDb(String db) {
        this.db = db;
    }

    /**
     * get 返回执行时间大于等于threshold的记录，默认10，单位秒
     *
     * @return
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * set 返回执行时间大于等于threshold的记录，默认10，单位秒
     *
     * @param threshold
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * get 显示数据的页码，默认为1，取值范围：[-1,1000)。pageNumber为-1时，返回所有数据页码；超过总页数时，显示最后一页。
     *
     * @return
     */
    public Integer getPageNumber() {
        return pageNumber;
    }

    /**
     * set 显示数据的页码，默认为1，取值范围：[-1,1000)。pageNumber为-1时，返回所有数据页码；超过总页数时，显示最后一页。
     *
     * @param pageNumber
     */
    public void setPageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
    }

    /**
     * get 每页显示的数据条数，默认为50，取值范围：[1,100]，只能为10的倍数
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set 每页显示的数据条数，默认为50，取值范围：[1,100]，只能为10的倍数
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * get 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * get RDS 实例ID，唯一标识一个RDS实例
     *
     * @return
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * set RDS 实例ID，唯一标识一个RDS实例
     *
     * @param instanceId
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }


    /**
     * set 需要查询的数据库名，多个数据库名之间用英文逗号分隔，默认所有数据库
     *
     * @param db
     */
    public DescribeActiveQueryPerformanceRequest db(String db) {
        this.db = db;
        return this;
    }

    /**
     * set 返回执行时间大于等于threshold的记录，默认10，单位秒
     *
     * @param threshold
     */
    public DescribeActiveQueryPerformanceRequest threshold(Integer threshold) {
        this.threshold = threshold;
        return this;
    }

    /**
     * set 显示数据的页码，默认为1，取值范围：[-1,1000)。pageNumber为-1时，返回所有数据页码；超过总页数时，显示最后一页。
     *
     * @param pageNumber
     */
    public DescribeActiveQueryPerformanceRequest pageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
        return this;
    }

    /**
     * set 每页显示的数据条数，默认为50，取值范围：[1,100]，只能为10的倍数
     *
     * @param pageSize
     */
    public DescribeActiveQueryPerformanceRequest pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * set 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
     *
     * @param regionId
     */
    public DescribeActiveQueryPerformanceRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }

    /**
     * set RDS 实例ID，唯一标识一个RDS实例
     *
     * @param instanceId
     */
    public DescribeActiveQueryPerformanceRequest instanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }


}