/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.monitor.model;

import java.util.List;
import java.util.ArrayList;

/**
 * metricGroup
 */
public class MetricGroup  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 自增id
     */
    private Integer id;

    /**
     * serviceCode
     */
    private String serviceCode;

    /**
     * groupCode
     */
    private String groupCode;

    /**
     * groupNameCH
     */
    private String groupNameCH;

    /**
     * groupNameEN
     */
    private String groupNameEN;

    /**
     * webCode
     */
    private String webCode;

    /**
     * mainTag
     */
    private String mainTag;

    /**
     * tags
     */
    private String tags;

    /**
     * parent
     */
    private Integer parent;

    /**
     * hasChildren
     */
    private Boolean hasChildren;

    /**
     * deletable
     */
    private Boolean deletable;

    /**
     * 业务线代码
     */
    private List<String> serviceCodes;

    /**
     * 排序字段
     */
    private String column;

    /**
     * 排序方式
     */
    private String dir;

    /**
     * 页码
     */
    private Integer number;

    /**
     * 查询条数
     */
    private Integer size;


    /**
     * get 自增id
     *
     * @return
     */
    public Integer getId() {
        return id;
    }

    /**
     * set 自增id
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * get serviceCode
     *
     * @return
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * set serviceCode
     *
     * @param serviceCode
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

    /**
     * get groupCode
     *
     * @return
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * set groupCode
     *
     * @param groupCode
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * get groupNameCH
     *
     * @return
     */
    public String getGroupNameCH() {
        return groupNameCH;
    }

    /**
     * set groupNameCH
     *
     * @param groupNameCH
     */
    public void setGroupNameCH(String groupNameCH) {
        this.groupNameCH = groupNameCH;
    }

    /**
     * get groupNameEN
     *
     * @return
     */
    public String getGroupNameEN() {
        return groupNameEN;
    }

    /**
     * set groupNameEN
     *
     * @param groupNameEN
     */
    public void setGroupNameEN(String groupNameEN) {
        this.groupNameEN = groupNameEN;
    }

    /**
     * get webCode
     *
     * @return
     */
    public String getWebCode() {
        return webCode;
    }

    /**
     * set webCode
     *
     * @param webCode
     */
    public void setWebCode(String webCode) {
        this.webCode = webCode;
    }

    /**
     * get mainTag
     *
     * @return
     */
    public String getMainTag() {
        return mainTag;
    }

    /**
     * set mainTag
     *
     * @param mainTag
     */
    public void setMainTag(String mainTag) {
        this.mainTag = mainTag;
    }

    /**
     * get tags
     *
     * @return
     */
    public String getTags() {
        return tags;
    }

    /**
     * set tags
     *
     * @param tags
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * get parent
     *
     * @return
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * set parent
     *
     * @param parent
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * get hasChildren
     *
     * @return
     */
    public Boolean getHasChildren() {
        return hasChildren;
    }

    /**
     * set hasChildren
     *
     * @param hasChildren
     */
    public void setHasChildren(Boolean hasChildren) {
        this.hasChildren = hasChildren;
    }

    /**
     * get deletable
     *
     * @return
     */
    public Boolean getDeletable() {
        return deletable;
    }

    /**
     * set deletable
     *
     * @param deletable
     */
    public void setDeletable(Boolean deletable) {
        this.deletable = deletable;
    }

    /**
     * get 业务线代码
     *
     * @return
     */
    public List<String> getServiceCodes() {
        return serviceCodes;
    }

    /**
     * set 业务线代码
     *
     * @param serviceCodes
     */
    public void setServiceCodes(List<String> serviceCodes) {
        this.serviceCodes = serviceCodes;
    }

    /**
     * get 排序字段
     *
     * @return
     */
    public String getColumn() {
        return column;
    }

    /**
     * set 排序字段
     *
     * @param column
     */
    public void setColumn(String column) {
        this.column = column;
    }

    /**
     * get 排序方式
     *
     * @return
     */
    public String getDir() {
        return dir;
    }

    /**
     * set 排序方式
     *
     * @param dir
     */
    public void setDir(String dir) {
        this.dir = dir;
    }

    /**
     * get 页码
     *
     * @return
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * set 页码
     *
     * @param number
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * get 查询条数
     *
     * @return
     */
    public Integer getSize() {
        return size;
    }

    /**
     * set 查询条数
     *
     * @param size
     */
    public void setSize(Integer size) {
        this.size = size;
    }


    /**
     * set 自增id
     *
     * @param id
     */
    public MetricGroup id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * set serviceCode
     *
     * @param serviceCode
     */
    public MetricGroup serviceCode(String serviceCode) {
        this.serviceCode = serviceCode;
        return this;
    }

    /**
     * set groupCode
     *
     * @param groupCode
     */
    public MetricGroup groupCode(String groupCode) {
        this.groupCode = groupCode;
        return this;
    }

    /**
     * set groupNameCH
     *
     * @param groupNameCH
     */
    public MetricGroup groupNameCH(String groupNameCH) {
        this.groupNameCH = groupNameCH;
        return this;
    }

    /**
     * set groupNameEN
     *
     * @param groupNameEN
     */
    public MetricGroup groupNameEN(String groupNameEN) {
        this.groupNameEN = groupNameEN;
        return this;
    }

    /**
     * set webCode
     *
     * @param webCode
     */
    public MetricGroup webCode(String webCode) {
        this.webCode = webCode;
        return this;
    }

    /**
     * set mainTag
     *
     * @param mainTag
     */
    public MetricGroup mainTag(String mainTag) {
        this.mainTag = mainTag;
        return this;
    }

    /**
     * set tags
     *
     * @param tags
     */
    public MetricGroup tags(String tags) {
        this.tags = tags;
        return this;
    }

    /**
     * set parent
     *
     * @param parent
     */
    public MetricGroup parent(Integer parent) {
        this.parent = parent;
        return this;
    }

    /**
     * set hasChildren
     *
     * @param hasChildren
     */
    public MetricGroup hasChildren(Boolean hasChildren) {
        this.hasChildren = hasChildren;
        return this;
    }

    /**
     * set deletable
     *
     * @param deletable
     */
    public MetricGroup deletable(Boolean deletable) {
        this.deletable = deletable;
        return this;
    }

    /**
     * set 业务线代码
     *
     * @param serviceCodes
     */
    public MetricGroup serviceCodes(List<String> serviceCodes) {
        this.serviceCodes = serviceCodes;
        return this;
    }

    /**
     * set 排序字段
     *
     * @param column
     */
    public MetricGroup column(String column) {
        this.column = column;
        return this;
    }

    /**
     * set 排序方式
     *
     * @param dir
     */
    public MetricGroup dir(String dir) {
        this.dir = dir;
        return this;
    }

    /**
     * set 页码
     *
     * @param number
     */
    public MetricGroup number(Integer number) {
        this.number = number;
        return this;
    }

    /**
     * set 查询条数
     *
     * @param size
     */
    public MetricGroup size(Integer size) {
        this.size = size;
        return this;
    }


    /**
     * add item to 业务线代码
     *
     * @param serviceCode
     */
    public void addServiceCode(String serviceCode) {
        if (this.serviceCodes == null) {
            this.serviceCodes = new ArrayList<>();
        }
        this.serviceCodes.add(serviceCode);
    }

}