/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.monitor.model;


/**
 * nsInfo
 */
public class NsInfo  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * namespace名字
     */
    private String namespaceName;

    /**
     * namespaceUUID
     */
    private String namespaceUuid;


    /**
     * get namespace名字
     *
     * @return
     */
    public String getNamespaceName() {
        return namespaceName;
    }

    /**
     * set namespace名字
     *
     * @param namespaceName
     */
    public void setNamespaceName(String namespaceName) {
        this.namespaceName = namespaceName;
    }

    /**
     * get namespaceUUID
     *
     * @return
     */
    public String getNamespaceUuid() {
        return namespaceUuid;
    }

    /**
     * set namespaceUUID
     *
     * @param namespaceUuid
     */
    public void setNamespaceUuid(String namespaceUuid) {
        this.namespaceUuid = namespaceUuid;
    }


    /**
     * set namespace名字
     *
     * @param namespaceName
     */
    public NsInfo namespaceName(String namespaceName) {
        this.namespaceName = namespaceName;
        return this;
    }

    /**
     * set namespaceUUID
     *
     * @param namespaceUuid
     */
    public NsInfo namespaceUuid(String namespaceUuid) {
        this.namespaceUuid = namespaceUuid;
        return this;
    }


}