/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 云硬盘相关接口
 * 云硬盘相关接口，提供批量创建云硬盘，查询云硬盘，删除云硬盘，对云硬盘进行扩容，修改云硬盘信息以及使用快照恢复云硬盘等功能。
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.disk.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.disk.model.DiskSpec;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 创建一块或多块云硬盘
 */
public class CreateDisksRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 创建云硬盘规格
     * Required:true
     */
    @Required
    private DiskSpec diskSpec;

    /**
     * 购买实例数量；取值范围：[1,100]
     * Required:true
     */
    @Required
    private Integer maxCount;

    /**
     * 幂等性校验参数
     * Required:true
     */
    @Required
    private String clientToken;

    /**
     * 地域ID
     * Required:true
     */
    @Required
    private String regionId;


    /**
     * get 创建云硬盘规格
     *
     * @return
     */
    public DiskSpec getDiskSpec() {
        return diskSpec;
    }

    /**
     * set 创建云硬盘规格
     *
     * @param diskSpec
     */
    public void setDiskSpec(DiskSpec diskSpec) {
        this.diskSpec = diskSpec;
    }

    /**
     * get 购买实例数量；取值范围：[1,100]
     *
     * @return
     */
    public Integer getMaxCount() {
        return maxCount;
    }

    /**
     * set 购买实例数量；取值范围：[1,100]
     *
     * @param maxCount
     */
    public void setMaxCount(Integer maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * get 幂等性校验参数
     *
     * @return
     */
    public String getClientToken() {
        return clientToken;
    }

    /**
     * set 幂等性校验参数
     *
     * @param clientToken
     */
    public void setClientToken(String clientToken) {
        this.clientToken = clientToken;
    }

    /**
     * get 地域ID
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * set 创建云硬盘规格
     *
     * @param diskSpec
     */
    public CreateDisksRequest diskSpec(DiskSpec diskSpec) {
        this.diskSpec = diskSpec;
        return this;
    }

    /**
     * set 购买实例数量；取值范围：[1,100]
     *
     * @param maxCount
     */
    public CreateDisksRequest maxCount(Integer maxCount) {
        this.maxCount = maxCount;
        return this;
    }

    /**
     * set 幂等性校验参数
     *
     * @param clientToken
     */
    public CreateDisksRequest clientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }

    /**
     * set 地域ID
     *
     * @param regionId
     */
    public CreateDisksRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


}