/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.starshield.model;


/**
 * describeOssRes
 */
public class DescribeOssRes  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * oss唯一id
     */
    private Number id;

    /**
     * 域名
     */
    private String zoneName;

    /**
     * 文件名称(oss key日期)
     */
    private String fileName;

    /**
     * 时间间隔类型(0-&gt;天 1-&gt;小时)
     */
    private Integer intervalType;

    /**
     * 文件格式(0-&gt;gz)
     */
    private Integer logType;

    /**
     * 开始时间
     */
    private String startTime;

    /**
     * 结束时间
     */
    private String endTime;

    /**
     * 日志数量
     */
    private Number totalCount;

    /**
     * 原始字节大小
     */
    private String byteCount;

    /**
     * 压缩文件大小
     */
    private String gzipByteCount;

    /**
     * 处理最后一个数据时间
     */
    private String lastTime;

    /**
     * oss key
     */
    private String ossKey;



    /**
     * get oss唯一id
     *
     * @return
     */
    public Number getId() {
        return id;
    }

    /**
     * set oss唯一id
     *
     * @param id
     */
    public void setId(Number id) {
        this.id = id;
    }


    /**
     * get 域名
     *
     * @return
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * set 域名
     *
     * @param zoneName
     */
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }


    /**
     * get 文件名称(oss key日期)
     *
     * @return
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * set 文件名称(oss key日期)
     *
     * @param fileName
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


    /**
     * get 时间间隔类型(0-&gt;天 1-&gt;小时)
     *
     * @return
     */
    public Integer getIntervalType() {
        return intervalType;
    }

    /**
     * set 时间间隔类型(0-&gt;天 1-&gt;小时)
     *
     * @param intervalType
     */
    public void setIntervalType(Integer intervalType) {
        this.intervalType = intervalType;
    }


    /**
     * get 文件格式(0-&gt;gz)
     *
     * @return
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * set 文件格式(0-&gt;gz)
     *
     * @param logType
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }


    /**
     * get 开始时间
     *
     * @return
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * set 开始时间
     *
     * @param startTime
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }


    /**
     * get 结束时间
     *
     * @return
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * set 结束时间
     *
     * @param endTime
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }


    /**
     * get 日志数量
     *
     * @return
     */
    public Number getTotalCount() {
        return totalCount;
    }

    /**
     * set 日志数量
     *
     * @param totalCount
     */
    public void setTotalCount(Number totalCount) {
        this.totalCount = totalCount;
    }


    /**
     * get 原始字节大小
     *
     * @return
     */
    public String getByteCount() {
        return byteCount;
    }

    /**
     * set 原始字节大小
     *
     * @param byteCount
     */
    public void setByteCount(String byteCount) {
        this.byteCount = byteCount;
    }


    /**
     * get 压缩文件大小
     *
     * @return
     */
    public String getGzipByteCount() {
        return gzipByteCount;
    }

    /**
     * set 压缩文件大小
     *
     * @param gzipByteCount
     */
    public void setGzipByteCount(String gzipByteCount) {
        this.gzipByteCount = gzipByteCount;
    }


    /**
     * get 处理最后一个数据时间
     *
     * @return
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * set 处理最后一个数据时间
     *
     * @param lastTime
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime;
    }


    /**
     * get oss key
     *
     * @return
     */
    public String getOssKey() {
        return ossKey;
    }

    /**
     * set oss key
     *
     * @param ossKey
     */
    public void setOssKey(String ossKey) {
        this.ossKey = ossKey;
    }



    /**
     * set oss唯一id
     *
     * @param id
     */
    public DescribeOssRes id(Number id) {
        this.id = id;
        return this;
    }


    /**
     * set 域名
     *
     * @param zoneName
     */
    public DescribeOssRes zoneName(String zoneName) {
        this.zoneName = zoneName;
        return this;
    }


    /**
     * set 文件名称(oss key日期)
     *
     * @param fileName
     */
    public DescribeOssRes fileName(String fileName) {
        this.fileName = fileName;
        return this;
    }


    /**
     * set 时间间隔类型(0-&gt;天 1-&gt;小时)
     *
     * @param intervalType
     */
    public DescribeOssRes intervalType(Integer intervalType) {
        this.intervalType = intervalType;
        return this;
    }


    /**
     * set 文件格式(0-&gt;gz)
     *
     * @param logType
     */
    public DescribeOssRes logType(Integer logType) {
        this.logType = logType;
        return this;
    }


    /**
     * set 开始时间
     *
     * @param startTime
     */
    public DescribeOssRes startTime(String startTime) {
        this.startTime = startTime;
        return this;
    }


    /**
     * set 结束时间
     *
     * @param endTime
     */
    public DescribeOssRes endTime(String endTime) {
        this.endTime = endTime;
        return this;
    }


    /**
     * set 日志数量
     *
     * @param totalCount
     */
    public DescribeOssRes totalCount(Number totalCount) {
        this.totalCount = totalCount;
        return this;
    }


    /**
     * set 原始字节大小
     *
     * @param byteCount
     */
    public DescribeOssRes byteCount(String byteCount) {
        this.byteCount = byteCount;
        return this;
    }


    /**
     * set 压缩文件大小
     *
     * @param gzipByteCount
     */
    public DescribeOssRes gzipByteCount(String gzipByteCount) {
        this.gzipByteCount = gzipByteCount;
        return this;
    }


    /**
     * set 处理最后一个数据时间
     *
     * @param lastTime
     */
    public DescribeOssRes lastTime(String lastTime) {
        this.lastTime = lastTime;
        return this;
    }


    /**
     * set oss key
     *
     * @param ossKey
     */
    public DescribeOssRes ossKey(String ossKey) {
        this.ossKey = ossKey;
        return this;
    }


}