/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CoreWebConsoleAPI
 * 控制台开放API
 *
 * OpenAPI spec version: v2
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.iotcore.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.iotcore.model.EventReportVo;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 设备事件查询
 */
public class DescribeEventListResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * pageSize
     */
    private Integer pageSize;

    /**
     * currentPage
     */
    private Integer currentPage;

    /**
     * totalCount
     */
    private Integer totalCount;

    /**
     * list
     */
    private List<EventReportVo> list;


    /**
     * get pageSize
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set pageSize
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * get currentPage
     *
     * @return
     */
    public Integer getCurrentPage() {
        return currentPage;
    }

    /**
     * set currentPage
     *
     * @param currentPage
     */
    public void setCurrentPage(Integer currentPage) {
        this.currentPage = currentPage;
    }

    /**
     * get totalCount
     *
     * @return
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * set totalCount
     *
     * @param totalCount
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * get list
     *
     * @return
     */
    public List<EventReportVo> getList() {
        return list;
    }

    /**
     * set list
     *
     * @param list
     */
    public void setList(List<EventReportVo> list) {
        this.list = list;
    }


    /**
     * set pageSize
     *
     * @param pageSize
     */
    public DescribeEventListResult pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * set currentPage
     *
     * @param currentPage
     */
    public DescribeEventListResult currentPage(Integer currentPage) {
        this.currentPage = currentPage;
        return this;
    }

    /**
     * set totalCount
     *
     * @param totalCount
     */
    public DescribeEventListResult totalCount(Integer totalCount) {
        this.totalCount = totalCount;
        return this;
    }

    /**
     * set list
     *
     * @param list
     */
    public DescribeEventListResult list(List<EventReportVo> list) {
        this.list = list;
        return this;
    }


    /**
     * add item to list
     *
     * @param list
     */
    public void addList(EventReportVo list) {
        if (this.list == null) {
            this.list = new ArrayList<>();
        }
        this.list.add(list);
    }

}