/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 域名url封禁类接口
 * Openapi For JCLOUD cdn
 *
 * OpenAPI spec version: v1
 * Contact: pid-cdn@jd.com
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.cdn.model;

import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 查询封禁信息
 */
public class QueryForbiddenInfoListRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 封禁域名,模糊查询
     */
    private String queryDomain;

    /**
     * 封禁url,精确查询
     */
    private String forbiddenUrl;

    /**
     * 页码数
     */
    private Integer pageNumber;

    /**
     * 每页size
     */
    private Integer pageSize;


    /**
     * get 封禁域名,模糊查询
     *
     * @return
     */
    public String getQueryDomain() {
        return queryDomain;
    }

    /**
     * set 封禁域名,模糊查询
     *
     * @param queryDomain
     */
    public void setQueryDomain(String queryDomain) {
        this.queryDomain = queryDomain;
    }

    /**
     * get 封禁url,精确查询
     *
     * @return
     */
    public String getForbiddenUrl() {
        return forbiddenUrl;
    }

    /**
     * set 封禁url,精确查询
     *
     * @param forbiddenUrl
     */
    public void setForbiddenUrl(String forbiddenUrl) {
        this.forbiddenUrl = forbiddenUrl;
    }

    /**
     * get 页码数
     *
     * @return
     */
    public Integer getPageNumber() {
        return pageNumber;
    }

    /**
     * set 页码数
     *
     * @param pageNumber
     */
    public void setPageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
    }

    /**
     * get 每页size
     *
     * @return
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * set 每页size
     *
     * @param pageSize
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }


    /**
     * set 封禁域名,模糊查询
     *
     * @param queryDomain
     */
    public QueryForbiddenInfoListRequest queryDomain(String queryDomain) {
        this.queryDomain = queryDomain;
        return this;
    }

    /**
     * set 封禁url,精确查询
     *
     * @param forbiddenUrl
     */
    public QueryForbiddenInfoListRequest forbiddenUrl(String forbiddenUrl) {
        this.forbiddenUrl = forbiddenUrl;
        return this;
    }

    /**
     * set 页码数
     *
     * @param pageNumber
     */
    public QueryForbiddenInfoListRequest pageNumber(Integer pageNumber) {
        this.pageNumber = pageNumber;
        return this;
    }

    /**
     * set 每页size
     *
     * @param pageSize
     */
    public QueryForbiddenInfoListRequest pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }


}