/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SCDN相关接口
 * Openapi For JCLOUD cdn
 *
 * OpenAPI spec version: v1
 * Contact: pid-cdn@jd.com
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.cdn.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.service.cdn.model.GeoArea;
import com.jdcloud.sdk.service.JdcloudResult;

/**
 * 查询geo地域
 */
public class QueryGeoAreasResult extends JdcloudResult implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * geoBlack
     */
    private List<GeoArea> geoBlack;


    /**
     * get geoBlack
     *
     * @return
     */
    public List<GeoArea> getGeoBlack() {
        return geoBlack;
    }

    /**
     * set geoBlack
     *
     * @param geoBlack
     */
    public void setGeoBlack(List<GeoArea> geoBlack) {
        this.geoBlack = geoBlack;
    }


    /**
     * set geoBlack
     *
     * @param geoBlack
     */
    public QueryGeoAreasResult geoBlack(List<GeoArea> geoBlack) {
        this.geoBlack = geoBlack;
        return this;
    }


    /**
     * add item to geoBlack
     *
     * @param geoBlack
     */
    public void addGeoBlack(GeoArea geoBlack) {
        if (this.geoBlack == null) {
            this.geoBlack = new ArrayList<>();
        }
        this.geoBlack.add(geoBlack);
    }

}