/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 实名认证-服务管理接口
 * 实名认证-服务管理接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.cloudauth.model;

import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 个人身份证OCR
 */
public class IDCardRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 身份证图像base64(支持base64编码后小于4M，分辨率不高于4096x4096的图像)
     * Required:true
     */
    @Required
    private String imageData;

    /**
     * front：身份证含照片的一面
back：身份证带国徽的一面
自动检测身份证正反面，如果传参指定方向与图片相反，支持正常识别，返回参数image_status字段为&quot;reversed_side&quot;

     * Required:true
     */
    @Required
    private String side;



    /**
     * get 身份证图像base64(支持base64编码后小于4M，分辨率不高于4096x4096的图像)
     *
     * @return
     */
    public String getImageData() {
        return imageData;
    }

    /**
     * set 身份证图像base64(支持base64编码后小于4M，分辨率不高于4096x4096的图像)
     *
     * @param imageData
     */
    public void setImageData(String imageData) {
        this.imageData = imageData;
    }


    /**
     * get front：身份证含照片的一面
back：身份证带国徽的一面
自动检测身份证正反面，如果传参指定方向与图片相反，支持正常识别，返回参数image_status字段为&quot;reversed_side&quot;

     *
     * @return
     */
    public String getSide() {
        return side;
    }

    /**
     * set front：身份证含照片的一面
back：身份证带国徽的一面
自动检测身份证正反面，如果传参指定方向与图片相反，支持正常识别，返回参数image_status字段为&quot;reversed_side&quot;

     *
     * @param side
     */
    public void setSide(String side) {
        this.side = side;
    }



    /**
     * set 身份证图像base64(支持base64编码后小于4M，分辨率不高于4096x4096的图像)
     *
     * @param imageData
     */
    public IDCardRequest imageData(String imageData) {
        this.imageData = imageData;
        return this;
    }


    /**
     * set front：身份证含照片的一面
back：身份证带国徽的一面
自动检测身份证正反面，如果传参指定方向与图片相反，支持正常识别，返回参数image_status字段为&quot;reversed_side&quot;

     *
     * @param side
     */
    public IDCardRequest side(String side) {
        this.side = side;
        return this;
    }


}