/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.privatezone.model;

import java.util.List;
import java.util.ArrayList;

/**
 * describeZonesRes
 */
public class DescribeZonesRes  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 域名id
     */
    private String zoneId;

    /**
     * 域名
     */
    private String zone;

    /**
     * 域名类型 LOCAL-&gt;云内全局 PTR-&gt;反向解析zone PV-&gt;私有zone
     */
    private String zoneType;

    /**
     * 解析记录个数
     */
    private Integer recordCount;

    /**
     * 是否锁定 true-&gt;锁定 false-&gt;未锁定
     */
    private Boolean lock;

    /**
     * 解析失败后是否进行递归解析
     */
    private Boolean retryRecurse;

    /**
     * 解析状态 NONE-&gt;没有解析 NORMAL-&gt;正常解析 PARTIAL-&gt;部分解析 PAUSE-&gt;暂停解析
     */
    private String resolveStatus;

    /**
     * 创建时间, UTC时间格式，例如2017-11-10T23:00:00Z
     */
    private String createTime;

    /**
     * 绑定的vpc信息
     */
    private List<DescribeBindVpcRes> bindVpc;


    /**
     * get 域名id
     *
     * @return
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * set 域名id
     *
     * @param zoneId
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * get 域名
     *
     * @return
     */
    public String getZone() {
        return zone;
    }

    /**
     * set 域名
     *
     * @param zone
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * get 域名类型 LOCAL-&gt;云内全局 PTR-&gt;反向解析zone PV-&gt;私有zone
     *
     * @return
     */
    public String getZoneType() {
        return zoneType;
    }

    /**
     * set 域名类型 LOCAL-&gt;云内全局 PTR-&gt;反向解析zone PV-&gt;私有zone
     *
     * @param zoneType
     */
    public void setZoneType(String zoneType) {
        this.zoneType = zoneType;
    }

    /**
     * get 解析记录个数
     *
     * @return
     */
    public Integer getRecordCount() {
        return recordCount;
    }

    /**
     * set 解析记录个数
     *
     * @param recordCount
     */
    public void setRecordCount(Integer recordCount) {
        this.recordCount = recordCount;
    }

    /**
     * get 是否锁定 true-&gt;锁定 false-&gt;未锁定
     *
     * @return
     */
    public Boolean getLock() {
        return lock;
    }

    /**
     * set 是否锁定 true-&gt;锁定 false-&gt;未锁定
     *
     * @param lock
     */
    public void setLock(Boolean lock) {
        this.lock = lock;
    }

    /**
     * get 解析失败后是否进行递归解析
     *
     * @return
     */
    public Boolean getRetryRecurse() {
        return retryRecurse;
    }

    /**
     * set 解析失败后是否进行递归解析
     *
     * @param retryRecurse
     */
    public void setRetryRecurse(Boolean retryRecurse) {
        this.retryRecurse = retryRecurse;
    }

    /**
     * get 解析状态 NONE-&gt;没有解析 NORMAL-&gt;正常解析 PARTIAL-&gt;部分解析 PAUSE-&gt;暂停解析
     *
     * @return
     */
    public String getResolveStatus() {
        return resolveStatus;
    }

    /**
     * set 解析状态 NONE-&gt;没有解析 NORMAL-&gt;正常解析 PARTIAL-&gt;部分解析 PAUSE-&gt;暂停解析
     *
     * @param resolveStatus
     */
    public void setResolveStatus(String resolveStatus) {
        this.resolveStatus = resolveStatus;
    }

    /**
     * get 创建时间, UTC时间格式，例如2017-11-10T23:00:00Z
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 创建时间, UTC时间格式，例如2017-11-10T23:00:00Z
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * get 绑定的vpc信息
     *
     * @return
     */
    public List<DescribeBindVpcRes> getBindVpc() {
        return bindVpc;
    }

    /**
     * set 绑定的vpc信息
     *
     * @param bindVpc
     */
    public void setBindVpc(List<DescribeBindVpcRes> bindVpc) {
        this.bindVpc = bindVpc;
    }


    /**
     * set 域名id
     *
     * @param zoneId
     */
    public DescribeZonesRes zoneId(String zoneId) {
        this.zoneId = zoneId;
        return this;
    }

    /**
     * set 域名
     *
     * @param zone
     */
    public DescribeZonesRes zone(String zone) {
        this.zone = zone;
        return this;
    }

    /**
     * set 域名类型 LOCAL-&gt;云内全局 PTR-&gt;反向解析zone PV-&gt;私有zone
     *
     * @param zoneType
     */
    public DescribeZonesRes zoneType(String zoneType) {
        this.zoneType = zoneType;
        return this;
    }

    /**
     * set 解析记录个数
     *
     * @param recordCount
     */
    public DescribeZonesRes recordCount(Integer recordCount) {
        this.recordCount = recordCount;
        return this;
    }

    /**
     * set 是否锁定 true-&gt;锁定 false-&gt;未锁定
     *
     * @param lock
     */
    public DescribeZonesRes lock(Boolean lock) {
        this.lock = lock;
        return this;
    }

    /**
     * set 解析失败后是否进行递归解析
     *
     * @param retryRecurse
     */
    public DescribeZonesRes retryRecurse(Boolean retryRecurse) {
        this.retryRecurse = retryRecurse;
        return this;
    }

    /**
     * set 解析状态 NONE-&gt;没有解析 NORMAL-&gt;正常解析 PARTIAL-&gt;部分解析 PAUSE-&gt;暂停解析
     *
     * @param resolveStatus
     */
    public DescribeZonesRes resolveStatus(String resolveStatus) {
        this.resolveStatus = resolveStatus;
        return this;
    }

    /**
     * set 创建时间, UTC时间格式，例如2017-11-10T23:00:00Z
     *
     * @param createTime
     */
    public DescribeZonesRes createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * set 绑定的vpc信息
     *
     * @param bindVpc
     */
    public DescribeZonesRes bindVpc(List<DescribeBindVpcRes> bindVpc) {
        this.bindVpc = bindVpc;
        return this;
    }


    /**
     * add item to 绑定的vpc信息
     *
     * @param bindVpc
     */
    public void addBindVpc(DescribeBindVpcRes bindVpc) {
        if (this.bindVpc == null) {
            this.bindVpc = new ArrayList<>();
        }
        this.bindVpc.add(bindVpc);
    }

}