/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.rocketmq.model;


/**
 * topic
 */
public class Topic  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * topic名称
     */
    private String topic;

    /**
     * 消息类型
     */
    private String topicType;

    /**
     * 描述
     */
    private String description;

    /**
     * 创建时间
     */
    private String createTime;

    /**
     * 分区数
     */
    private Integer queueNums;



    /**
     * get topic名称
     *
     * @return
     */
    public String getTopic() {
        return topic;
    }

    /**
     * set topic名称
     *
     * @param topic
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }


    /**
     * get 消息类型
     *
     * @return
     */
    public String getTopicType() {
        return topicType;
    }

    /**
     * set 消息类型
     *
     * @param topicType
     */
    public void setTopicType(String topicType) {
        this.topicType = topicType;
    }


    /**
     * get 描述
     *
     * @return
     */
    public String getDescription() {
        return description;
    }

    /**
     * set 描述
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }


    /**
     * get 创建时间
     *
     * @return
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * set 创建时间
     *
     * @param createTime
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }


    /**
     * get 分区数
     *
     * @return
     */
    public Integer getQueueNums() {
        return queueNums;
    }

    /**
     * set 分区数
     *
     * @param queueNums
     */
    public void setQueueNums(Integer queueNums) {
        this.queueNums = queueNums;
    }



    /**
     * set topic名称
     *
     * @param topic
     */
    public Topic topic(String topic) {
        this.topic = topic;
        return this;
    }


    /**
     * set 消息类型
     *
     * @param topicType
     */
    public Topic topicType(String topicType) {
        this.topicType = topicType;
        return this;
    }


    /**
     * set 描述
     *
     * @param description
     */
    public Topic description(String description) {
        this.description = description;
        return this;
    }


    /**
     * set 创建时间
     *
     * @param createTime
     */
    public Topic createTime(String createTime) {
        this.createTime = createTime;
        return this;
    }


    /**
     * set 分区数
     *
     * @param queueNums
     */
    public Topic queueNums(Integer queueNums) {
        this.queueNums = queueNums;
        return this;
    }


}