/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 弹性伸缩管理
 * 弹性伸缩功能的接口
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.ag.model;

import java.util.List;
import java.util.ArrayList;
import com.jdcloud.sdk.annotation.Required;
import com.jdcloud.sdk.service.JdcloudRequest;

/**
 * 弹性伸缩组内资源是否托管修改
 */
public class ModifyInstancesManagedRequest extends JdcloudRequest implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 实例是否托管给弹性伸缩组，托管后缩容时可以删除该实例。
     * Required:true
     */
    @Required
    private Boolean isManaged;

    /**
     * 资源ID数组。
     * Required:true
     */
    @Required
    
    private List<String> instanceIds;
    /**
     * 地域
     * Required:true
     */
    @Required
    private String regionId;

    /**
     * 高可用组 ID
     * Required:true
     */
    @Required
    private String agId;



    /**
     * get 实例是否托管给弹性伸缩组，托管后缩容时可以删除该实例。
     *
     * @return
     */
    public Boolean getIsManaged() {
        return isManaged;
    }

    /**
     * set 实例是否托管给弹性伸缩组，托管后缩容时可以删除该实例。
     *
     * @param isManaged
     */
    public void setIsManaged(Boolean isManaged) {
        this.isManaged = isManaged;
    }


    /**
    * get 资源ID数组。
    *
    * @return
    */
    public List<String> getInstanceIds() {
        return instanceIds;
    }

    /**
    * set 资源ID数组。
    *
    * @param instanceIds
    */
    public void setInstanceIds(List<String> instanceIds) {
        this.instanceIds = instanceIds;
    }


    /**
     * get 地域
     *
     * @return
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * set 地域
     *
     * @param regionId
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }


    /**
     * get 高可用组 ID
     *
     * @return
     */
    public String getAgId() {
        return agId;
    }

    /**
     * set 高可用组 ID
     *
     * @param agId
     */
    public void setAgId(String agId) {
        this.agId = agId;
    }



    /**
     * set 实例是否托管给弹性伸缩组，托管后缩容时可以删除该实例。
     *
     * @param isManaged
     */
    public ModifyInstancesManagedRequest isManaged(Boolean isManaged) {
        this.isManaged = isManaged;
        return this;
    }


    /**
    * set 资源ID数组。
    *
    * @param instanceIds
    */
    public ModifyInstancesManagedRequest instanceIds(List<String> instanceIds) {
        this.instanceIds = instanceIds;
        return this;
    }


    /**
     * set 地域
     *
     * @param regionId
     */
    public ModifyInstancesManagedRequest regionId(String regionId) {
        this.regionId = regionId;
        return this;
    }


    /**
     * set 高可用组 ID
     *
     * @param agId
     */
    public ModifyInstancesManagedRequest agId(String agId) {
        this.agId = agId;
        return this;
    }



    /**
     * add item to 资源ID数组。
     *
     * @param instanceId
     */
    public void addInstanceId(String instanceId) {
        if (this.instanceIds == null) {
            this.instanceIds = new ArrayList<>();
        }
        this.instanceIds.add(instanceId);
    }
}