/*
 * Copyright 2018 JDCLOUD.COM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http:#www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * 
 * 
 *
 * 
 * Contact: 
 *
 * NOTE: This class is auto generated by the jdcloud code generator program.
 */

package com.jdcloud.sdk.service.jdfusion.model;


/**
 * RDS数据库上的账号权限
 */
public class RdsDBAccessPrivilege  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 账号名称
     */
    private String accountName;

    /**
     * 账号对数据库所具有的权限
     */
    private String privilege;

    /**
     * 所属云提供商ID
     */
    private String cloudID;


    /**
     * get 账号名称
     *
     * @return
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * set 账号名称
     *
     * @param accountName
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * get 账号对数据库所具有的权限
     *
     * @return
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * set 账号对数据库所具有的权限
     *
     * @param privilege
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    /**
     * get 所属云提供商ID
     *
     * @return
     */
    public String getCloudID() {
        return cloudID;
    }

    /**
     * set 所属云提供商ID
     *
     * @param cloudID
     */
    public void setCloudID(String cloudID) {
        this.cloudID = cloudID;
    }


    /**
     * set 账号名称
     *
     * @param accountName
     */
    public RdsDBAccessPrivilege accountName(String accountName) {
        this.accountName = accountName;
        return this;
    }

    /**
     * set 账号对数据库所具有的权限
     *
     * @param privilege
     */
    public RdsDBAccessPrivilege privilege(String privilege) {
        this.privilege = privilege;
        return this;
    }

    /**
     * set 所属云提供商ID
     *
     * @param cloudID
     */
    public RdsDBAccessPrivilege cloudID(String cloudID) {
        this.cloudID = cloudID;
        return this;
    }


}